-- Comprobacion de choques: las 1162 descripciones que traen los layouts,
-- contra lo que ya esta en el catalogo de productos.
--
-- SOLO LECTURA. Si devuelve cero filas, la carga no duplica nada.
-- Cada fila que salga es un articulo que YA existe y que la carga volveria a
-- dar de alta con codigo nuevo, porque CargaInicialSeeder no deduplica.

WITH layout(descripcion, almacen, obra, tipo) AS (
  VALUES
    ('CABLE DE USO RUDO 2X12', 'CONST', 'MBP', 'insumo'),
    ('CABLE DE USO RUDO 2X8', 'CONST', 'MBP', 'insumo'),
    ('CABLE PORTAELECTRODO 1/0', 'CONST', 'MBP', 'insumo'),
    ('ESCALERA DE TIJERA', 'CONST', 'MBP', 'insumo'),
    ('ESCALERA TELESCOPICA', 'CONST', 'MBP', 'insumo'),
    ('ESCALERA MULTIPOSICION', 'CONST', 'MBP', 'insumo'),
    ('ESLINGA DE 4 MTS', 'CONST', 'MBP', 'insumo'),
    ('CINCEL DE CORTE FRIO', 'CONST', 'MBP', 'insumo'),
    ('REFLECTORES PARA EXTERIOR', 'CONST', 'MBP', 'insumo'),
    ('CRUCETA DE ANDAMIO', 'CONST', 'MBP', 'insumo'),
    ('MARCO DE ANDAMIO', 'CONST', 'MBP', 'insumo'),
    ('PLATAFORMA DE ANDAMIO', 'CONST', 'MBP', 'insumo'),
    ('RUEDA DE ANDAMIO', 'CONST', 'MBP', 'insumo'),
    ('ARNES DE CUERPO COMPLETO', 'CONST', 'MBP', 'insumo'),
    ('LINEA DE VIDA DOBLE GANCHO GRANDE C', 'CONST', 'MBP', 'insumo'),
    ('CARETAS FACIALES', 'CONST', 'MBP', 'insumo'),
    ('CABLE PORTAELECTRODO 1/0', 'CONST', 'PARKS NAVE A', 'insumo'),
    ('CABLE DE USO RUDO 2X12', 'CONST', 'PARKS NAVE A', 'insumo'),
    ('CABLE DE USO RUDO 2X8', 'CONST', 'PARKS NAVE A', 'insumo'),
    ('MANGUERA NEUMATICA', 'CONST', 'PARKS NAVE A', 'insumo'),
    ('LONAS INGNIFUGAS', 'CONST', 'PARKS NAVE A', 'insumo'),
    ('DADOS DE IMPACTO', 'CONST', 'PARKS NAVE A', 'insumo'),
    ('REFLECTORES PARA EXTERIOR', 'CONST', 'PARKS NAVE A', 'insumo'),
    ('TABLERO ELECTRICO', 'CONST', 'PARKS NAVE A', 'insumo'),
    ('TANQUES DE GAS 20 KG', 'CONST', 'PARKS NAVE A', 'insumo'),
    ('TANQUES OXIGENO 9 M3', 'CONST', 'PARKS NAVE A', 'insumo'),
    ('CINCEL DE CORTE FRIO', 'CONST', 'PARKS NAVE A', 'insumo'),
    ('ESCUADRA DE METAL 12"', 'CONST', 'PARKS NAVE A', 'insumo'),
    ('LINEA DE VIDA DOBLE GANCHO GRANDE C', 'CONST', 'PARKS NAVE A', 'insumo'),
    ('CABLE DE ALUMINIO', 'CONST', 'SIX PARKS CANCUN', 'insumo'),
    ('TANQUES OXIGENO 9 M3', 'CONST', 'SIX PARKS CANCUN', 'insumo'),
    ('ESCALERA TELESCOPICA', 'CONST', 'SIX PARKS CANCUN', 'insumo'),
    ('IMPRESORA', 'CONST', 'SIX PARKS CANCUN', 'insumo'),
    ('MESA', 'CONST', 'SIX PARKS CANCUN', 'insumo'),
    ('SILLAS PEGABLES', 'CONST', 'SIX PARKS CANCUN', 'insumo'),
    ('TABLERO ELECTRICO', 'CONST', 'SIX PARKS CANCUN', 'insumo'),
    ('ARNES DE CUERPO COMPLETO', 'CONST', 'SIX PARKS CANCUN', 'insumo'),
    ('LINEA DE VIDA DOBLE GANCHO GRANDE C', 'CONST', 'SIX PARKS CANCUN', 'insumo'),
    ('LLAVE PERICA CROMADA DE 15"', 'CONST', 'SIX PARKS CANCUN', 'insumo'),
    ('LLAVE PERICA CROMADA DE 8"', 'CONST', 'SIX PARKS CANCUN', 'insumo'),
    ('CABLE DE USO RUDO 3X10', 'CONST', 'TRES GUERRAS', 'insumo'),
    ('CABLE DE USO RUDO 3X8', 'CONST', 'TRES GUERRAS', 'insumo'),
    ('CARRITOS DE OXICORTE', 'CONST', 'TRES GUERRAS', 'insumo'),
    ('EQUIPO DE OXICORTE COMPLETO', 'CONST', 'TRES GUERRAS', 'insumo'),
    ('TANQUES DE GAS 20 KG', 'CONST', 'TRES GUERRAS', 'insumo'),
    ('TANQUES OXIGENO 9 M3', 'CONST', 'TRES GUERRAS', 'insumo'),
    ('DADOS DE IMPACTO', 'CONST', 'TRES GUERRAS', 'insumo'),
    ('TABLERO ELECTRICO', 'CONST', 'TRES GUERRAS', 'insumo'),
    ('ARNES DE CUERPO COMPLETO', 'CONST', 'TRES GUERRAS', 'insumo'),
    ('LINEA DE VIDA DOBLE GANCHO GRANDE C', 'CONST', 'TRES GUERRAS', 'insumo'),
    ('POSTES DE SEÑALAMIENTO TIPO VELA', 'CONST', 'TRES GUERRAS', 'insumo'),
    ('EXTINTORES PQS 4.5 KG', 'CONST', 'TRES GUERRAS', 'insumo'),
    ('CABLE DE ACERO FLEXIBLE', 'CONST', 'TRES GUERRAS', 'insumo'),
    ('MESA', 'CONST', 'TRES GUERRAS', 'insumo'),
    ('SILLAS PEGABLES', 'CONST', 'TRES GUERRAS', 'insumo'),
    ('CABLE DE USO RUDO 2X12', 'CONST', 'AMPLIACION T4', 'insumo'),
    ('CABLE DE USO RUDO 2X8', 'CONST', 'AMPLIACION T4', 'insumo'),
    ('CABLE DE USO RUDO 3X8', 'CONST', 'AMPLIACION T4', 'insumo'),
    ('CABLE PORTAELECTRODO 1/0', 'CONST', 'AMPLIACION T4', 'insumo'),
    ('CABLE TIERRA 1/0', 'CONST', 'AMPLIACION T4', 'insumo'),
    ('CABLE DE ALUMINIO', 'CONST', 'AMPLIACION T4', 'insumo'),
    ('EQUIPO DE OXICORTE COMPLETO', 'CONST', 'AMPLIACION T4', 'insumo'),
    ('SOPLETE DE CORTE OXIGENO-ACETILENO', 'CONST', 'AMPLIACION T4', 'insumo'),
    ('ESLINGA DE 6 MTS', 'CONST', 'AMPLIACION T4', 'insumo'),
    ('ESLINGA DE 12 MTS', 'CONST', 'AMPLIACION T4', 'insumo'),
    ('MARRO DE ACERO GRANDE', 'CONST', 'AMPLIACION T4', 'insumo'),
    ('MARRO DE ACERO PEQUEÑO', 'CONST', 'AMPLIACION T4', 'insumo'),
    ('CINCEL DE CORTE FRIO', 'CONST', 'AMPLIACION T4', 'insumo'),
    ('NIVEL DE MANO DE 18"', 'CONST', 'AMPLIACION T4', 'insumo'),
    ('NIVEL DE MANO DE 24"', 'CONST', 'AMPLIACION T4', 'insumo'),
    ('NIVEL DE MANO DE 36"', 'CONST', 'AMPLIACION T4', 'insumo'),
    ('ESCUADRA DE METAL DE 12"', 'CONST', 'AMPLIACION T4', 'insumo'),
    ('ESCUADRA DE METAL DE 16"', 'CONST', 'AMPLIACION T4', 'insumo'),
    ('LLAVES ESPAÑOLAS', 'CONST', 'AMPLIACION T4', 'insumo'),
    ('LLAVE COMBINADA ESTANDAR 1/2', 'CONST', 'AMPLIACION T4', 'insumo'),
    ('LLAVE COMBINADA ESTANDAR 5/8', 'CONST', 'AMPLIACION T4', 'insumo'),
    ('LLAVE STILSON', 'CONST', 'AMPLIACION T4', 'insumo'),
    ('DADOS DE IMPACTO', 'CONST', 'AMPLIACION T4', 'insumo'),
    ('POLIPASTO MANUAL 5 TON', 'CONST', 'AMPLIACION T4', 'insumo'),
    ('POLIPASTO ELECTRICO 1 TON', 'CONST', 'AMPLIACION T4', 'insumo'),
    ('REFLECTORES PARA EXTERIOR', 'CONST', 'AMPLIACION T4', 'insumo'),
    ('LUMINARIA SOLAR PARA BARRICADA BASE AMBAR- DESTELL ROJO', 'CONST', 'AMPLIACION T4', 'insumo'),
    ('LUZ ESTROBOSCOPICA', 'CONST', 'AMPLIACION T4', 'insumo'),
    ('TABLERO ELECTRICO', 'CONST', 'AMPLIACION T4', 'insumo'),
    ('BIDON TANQUE DE ACERO INOXIDABLE', 'CONST', 'AMPLIACION T4', 'insumo'),
    ('ARNES DE CUERPO COMPLETO', 'CONST', 'AMPLIACION T4', 'insumo'),
    ('LINEA DE VIDA DOBLE GANCHO GRANDE C', 'CONST', 'AMPLIACION T4', 'insumo'),
    ('CARETA DE SOLDADOR', 'CONST', 'AMPLIACION T4', 'insumo'),
    ('CARETAS FACIALES', 'CONST', 'AMPLIACION T4', 'insumo'),
    ('EXTINTORES PQS 1 KG', 'CONST', 'AMPLIACION T4', 'insumo'),
    ('EXTINTORES PQS 4.5 KG', 'CONST', 'AMPLIACION T4', 'insumo'),
    ('EXTINTORES PQS 6 KG', 'CONST', 'AMPLIACION T4', 'insumo'),
    ('EXTINTORES PQS 9 KG', 'CONST', 'AMPLIACION T4', 'insumo'),
    ('BAUMANOMETRO', 'CONST', 'AMPLIACION T4', 'insumo'),
    ('CABLE DE ACERO FLEXIBLE', 'CONST', 'AMPLIACION T4', 'insumo'),
    ('PUNTO FIJO', 'CONST', 'AMPLIACION T4', 'insumo'),
    ('PATAS DE CABRA', 'CONST', 'AMPLIACION T4', 'insumo'),
    ('MAZO DE GOMA', 'CONST', 'AMPLIACION T4', 'insumo'),
    ('LAMPARA DE MANO', 'CONST', 'AMPLIACION T4', 'insumo'),
    ('BOTIQUIN PRIMEROS AUXILIOS', 'CONST', 'AMPLIACION T4', 'insumo'),
    ('EQUIPO DE OXICORTE COMPLETO', 'CONST', 'TERRAZA ERNESTO ROSADO', 'insumo'),
    ('TANQUES DE GAS 20 KG', 'CONST', 'TERRAZA ERNESTO ROSADO', 'insumo'),
    ('TANQUES OXIGENO 9 M3', 'CONST', 'TERRAZA ERNESTO ROSADO', 'insumo'),
    ('CARRITOS DE OXICORTE', 'CONST', 'TERRAZA ERNESTO ROSADO', 'insumo'),
    ('MARCO DE ANDAMIO', 'CONST', 'TERRAZA ERNESTO ROSADO', 'insumo'),
    ('CRUCETA DE ANDAMIO', 'CONST', 'TERRAZA ERNESTO ROSADO', 'insumo'),
    ('PLATAFORMA DE ANDAMIO', 'CONST', 'TERRAZA ERNESTO ROSADO', 'insumo'),
    ('MANOMETRO DE OXIGENO', 'CONST', 'TERRAZA ERNESTO ROSADO', 'insumo'),
    ('ADAPTADOR FACIAL PARA CASCO', 'CONS', 'central', 'insumo'),
    ('AISLADOR', 'CONS', 'central', 'insumo'),
    ('ARNES DE CUERPO COMPLETO', 'CONS', 'central', 'insumo'),
    ('ARRANCADOR MAGNETICO A TENSION', 'CONS', 'central', 'insumo'),
    ('BANDERA DE PRECAUCION', 'CONS', 'central', 'insumo'),
    ('BOMBA EXTRACTOR', 'CONS', 'central', 'insumo'),
    ('BOQUILLA DE OXICORTE #2', 'CONS', 'central', 'insumo'),
    ('BORNES INDUSTRIAL', 'CONS', 'central', 'insumo'),
    ('BOTES DE AGUA', 'CONS', 'central', 'insumo'),
    ('BOTIQUIN PRIMEROS AUXILIOS', 'CONS', 'central', 'insumo'),
    ('BROCA DE 7/16', 'CONS', 'central', 'insumo'),
    ('CADENA DE ACERO', 'CONS', 'central', 'insumo'),
    ('CADENA DE PLASTICO', 'CONS', 'central', 'insumo'),
    ('CAMARA DE SEGURIDAD', 'CONS', 'central', 'insumo'),
    ('CARETA FACIAL', 'CONS', 'central', 'insumo'),
    ('CARGADOR PARA RADIO', 'CONS', 'central', 'insumo'),
    ('CARRIL PARA SOGA', 'CONS', 'central', 'insumo'),
    ('CASCO AZUL', 'CONS', 'central', 'insumo'),
    ('CAUCHO BUTILICO', 'CONS', 'central', 'insumo'),
    ('CEPILLO DE ALAMBRE', 'CONS', 'central', 'insumo'),
    ('CHALUPA', 'CONS', 'central', 'insumo'),
    ('CHISPERO', 'CONS', 'central', 'insumo'),
    ('CINTA DE PRECAUCION', 'CONS', 'central', 'insumo'),
    ('CINTA DOBLE CARA', 'CONS', 'central', 'insumo'),
    ('CINTA TEFLON', 'CONS', 'central', 'insumo'),
    ('CLAVIJA 110V', 'CONS', 'central', 'insumo'),
    ('CLAVIJA TRIFASICA', 'CONS', 'central', 'insumo'),
    ('CONECTOR RAPIDO HEMBRA', 'CONS', 'central', 'insumo'),
    ('CONECTOR RAPIDO MACHO', 'CONS', 'central', 'insumo'),
    ('CONECTOR RAPIDO PARA MAQUINA MACHO', 'CONS', 'central', 'insumo'),
    ('CONO PRECUCION', 'CONS', 'central', 'insumo'),
    ('CONTACTO DUPLEX', 'CONS', 'central', 'insumo'),
    ('CRISTAL SOMBRA #11', 'CONS', 'central', 'insumo'),
    ('CRISTAL SOMBRA #12', 'CONS', 'central', 'insumo'),
    ('CRISTAL CLAROS', 'CONS', 'central', 'insumo'),
    ('DISCO LAMINADO 4 1/2"', 'CONS', 'central', 'insumo'),
    ('ESCUADRA', 'CONS', 'central', 'insumo'),
    ('GRILLETES', 'CONS', 'central', 'insumo'),
    ('GUANTES DE BOLITA', 'CONS', 'central', 'insumo'),
    ('GUANTES DE CARNAZA CORTOS', 'CONS', 'central', 'insumo'),
    ('GUANTES DE NITRILO', 'CONS', 'central', 'insumo'),
    ('GUARDA PARA ESMERIL', 'CONS', 'central', 'insumo'),
    ('GUARDA PARA MINI ESMERIL', 'CONS', 'central', 'insumo'),
    ('JARRAS P/PINTURA', 'CONS', 'central', 'insumo'),
    ('JUEGO DE ARRESTAFLAMA', 'CONS', 'central', 'insumo'),
    ('LENTES CLAROS', 'CONS', 'central', 'insumo'),
    ('LIMPIA BOQUILLA', 'CONS', 'central', 'insumo'),
    ('LINEA DE VIDA DOBLE GANCHO GRANDE C', 'CONS', 'central', 'insumo'),
    ('LLAVE PARA MINI ESMERIL', 'CONS', 'central', 'insumo'),
    ('LONA', 'CONS', 'central', 'insumo'),
    ('MALLA POLINET (NUEVA)', 'CONS', 'central', 'insumo'),
    ('MALLA POLINET (USADA)', 'CONS', 'central', 'insumo'),
    ('MANERAL PARA ESMERIL', 'CONS', 'central', 'insumo'),
    ('MANERAL PARA MINI RODILLO', 'CONS', 'central', 'insumo'),
    ('MANGAS DE CARNAZA', 'CONS', 'central', 'insumo'),
    ('MANOMETRO', 'CONS', 'central', 'insumo'),
    ('MAROMA PARA CARETA FACIAL', 'CONS', 'central', 'insumo'),
    ('MAZO DE GOMA', 'CONS', 'central', 'insumo'),
    ('MARRO DE ACERO GRANDE', 'CONS', 'central', 'insumo'),
    ('MARRO DE ACERO PEQUEÑO', 'CONS', 'central', 'insumo'),
    ('LLANA TRUPPER', 'CONS', 'central', 'insumo'),
    ('MESA', 'CONS', 'central', 'insumo'),
    ('MICA DE CARETA FACIAL', 'CONS', 'central', 'insumo'),
    ('NIVEL DE MANO 14', 'CONS', 'central', 'insumo'),
    ('NIVEL DE MANO 18', 'CONS', 'central', 'insumo'),
    ('NIVEL DE MANO 24', 'CONS', 'central', 'insumo'),
    ('NIVEL DE MANO 48', 'CONS', 'central', 'insumo'),
    ('NUDOS PARA CABLE 1/4', 'CONS', 'central', 'insumo'),
    ('PASTILLA DE CORRIENTE', 'CONS', 'central', 'insumo'),
    ('PETOS (MANDILES)', 'CONS', 'central', 'insumo'),
    ('PISTOLA PARA PINTURA CALEFACCION', 'CONS', 'central', 'insumo'),
    ('PLACA PARA CONTACTO', 'CONS', 'central', 'insumo'),
    ('POLAINAS (BOTERAS)', 'CONS', 'central', 'insumo'),
    ('BROCA DE 1', 'CONS', 'central', 'insumo'),
    ('RADIOS', 'CONS', 'central', 'insumo'),
    ('RAFIA', 'CONS', 'central', 'insumo'),
    ('RECOGEDOR', 'CONS', 'central', 'insumo'),
    ('REFLECTORES PARA EXTERIOR', 'CONS', 'central', 'insumo'),
    ('REFLECTORES', 'CONS', 'central', 'insumo'),
    ('REGULADOR', 'CONS', 'central', 'insumo'),
    ('RUEDA DE ANDAMIO', 'CONS', 'central', 'insumo'),
    ('SARGENTO DE SOLERA', 'CONS', 'central', 'insumo'),
    ('SEÑALAMIENTOS SEGURIDAD', 'CONS', 'central', 'insumo'),
    ('SILLAS PLEGABLES', 'CONS', 'central', 'insumo'),
    ('SISTEMA AUTORECTATIL', 'CONS', 'central', 'insumo'),
    ('TAPONES AUDITIVOS', 'CONS', 'central', 'insumo'),
    ('TINACO', 'CONS', 'central', 'insumo'),
    ('VALVULA PARA COMPRESOR DE AIRE', 'CONS', 'central', 'insumo'),
    ('VENTILADORES', 'CONS', 'central', 'insumo'),
    ('BARRETA DE UÑA', 'CONS', 'central', 'insumo'),
    ('CONOS NARANJA', 'CONS', 'central', 'insumo'),
    ('CARDA DE 4"', 'CONS', 'central', 'insumo'),
    ('CARDA DE 5"', 'CONS', 'central', 'insumo'),
    ('CARDA MULTIROSCA', 'CONS', 'central', 'insumo'),
    ('DISCO DE DESBASTE 9"', 'CONS', 'central', 'insumo'),
    ('PLACA ABS', 'CONS', 'central', 'insumo'),
    ('CONTACTO 110 V', 'CONS', 'central', 'insumo'),
    ('BOQUILLA DE OXICORTE #3', 'CONS', 'central', 'insumo'),
    ('SILICON DURETAN', 'CONS', 'central', 'insumo'),
    ('CARRITOS DE OXICORTE', 'CONS', 'central', 'insumo'),
    ('EQUIPO DE OXICORTE COMPLETO', 'CONS', 'central', 'insumo'),
    ('EXTINTORES PQS 6 KG', 'CONS', 'central', 'insumo'),
    ('EXTINTORES PQS 4.5 KG', 'CONS', 'central', 'insumo'),
    ('EXTINTORES PQS 9 KG', 'CONS', 'central', 'insumo'),
    ('TANQUES DE GAS 20 KG', 'CONS', 'central', 'insumo'),
    ('TANQUES OXIGENO 9 M3', 'CONS', 'central', 'insumo'),
    ('TANQUES DE ACETILENO', 'CONS', 'central', 'insumo'),
    ('CLIPS Y BASE MOVIL 180', 'CONS', 'central', 'insumo'),
    ('BASE CLIP 180/90', 'CONS', 'central', 'insumo'),
    ('BASE CLIP MULTIMURO', 'CONS', 'central', 'insumo'),
    ('BASE PARA CLIP 90', 'CONS', 'central', 'insumo'),
    ('PERNO NELSON 3/4 X 7 3/4', 'CONS', 'central', 'insumo'),
    ('BIRLO GALVANIZADO A-307 DE 1/2 X 5', 'CONS', 'central', 'insumo'),
    ('PERNO NELSON 3/8 X 7', 'CONS', 'central', 'insumo'),
    ('PERNO NELSON DE 3/4 X 7 3/4', 'CONS', 'central', 'insumo'),
    ('RONDANA GALVANIZADA A-307 DE 7/8', 'CONS', 'central', 'insumo'),
    ('TUERCA GALVANIZADA A-325 DE 7/8', 'CONS', 'central', 'insumo'),
    ('BIRLO NEGRA A-325 DE 3/8 X 9', 'CONS', 'central', 'insumo'),
    ('TORNILLO GALVANIZADO A-307 DE 3/8 X 5', 'CONS', 'central', 'insumo'),
    ('TORNILLO CONTROL VOLT  A-490 7/8 X 3 1/4', 'CONS', 'central', 'insumo'),
    ('TORNILLO GALVANIZADA A-307 DE 1/2 X 5 1/2', 'CONS', 'central', 'insumo'),
    ('TUERCA NEGRA A-325 DE 1 1/8', 'CONS', 'central', 'insumo'),
    ('TORNILLO GALVANIZADO A-307 DE 3/8 X 7', 'CONS', 'central', 'insumo'),
    ('TORNILLO NEGRO A-325 DE 3/8 X 7', 'CONS', 'central', 'insumo'),
    ('RONDANA GALVANIZADA A-436 DE 1 3/4', 'CONS', 'central', 'insumo'),
    ('RONDANA NEGRA A-325 DE 1 1/2', 'CONS', 'central', 'insumo'),
    ('TORNILLO GALVANIZADO A-307 DE 1/2 X 6 1/2', 'CONS', 'central', 'insumo'),
    ('TORNILLO GALV A-325 DE 3/8 X 8', 'CONS', 'central', 'insumo'),
    ('TORNILLO NEGRO A-490 DE 3/4 X 3', 'CONS', 'central', 'insumo'),
    ('TONILLO CONTROL VOLT A-490 DE 1 1/8 X 3 1/4', 'CONS', 'central', 'insumo'),
    ('TUERCA GALVANIZADO A-325 DE 1 1/2', 'CONS', 'central', 'insumo'),
    ('TUERCA GALVANIZADO A-325 DE 1 1/8', 'CONS', 'central', 'insumo'),
    ('RONDANA NEGRA A-4436 DE 1 1/4', 'CONS', 'central', 'insumo'),
    ('TORNILLO CONTROL VOLT 1 1/8 X 7 1/2', 'CONS', 'central', 'insumo'),
    ('RONDANA GALV A-307 DE 1 1/2', 'CONS', 'central', 'insumo'),
    ('RONDANA GALVANIZADA A-436 DE 1 1/2', 'CONS', 'central', 'insumo'),
    ('RONDANA GALV A-307 DE 3/4', 'CONS', 'central', 'insumo'),
    ('TORNILLO NEGRO A-325 DE 1 X 3 1/4', 'CONS', 'central', 'insumo'),
    ('TORNILLO GALVANIZADA A-307 DE 1/2 X 6', 'CONS', 'central', 'insumo'),
    ('TORNILLO GALVANIZADA A-307 DE 3/8 X 6 1/2', 'CONS', 'central', 'insumo'),
    ('TORNILLO  GALVANIZADA A307 DE 1/2 X 8 1/4', 'CONS', 'central', 'insumo'),
    ('TORNILLO GALVANIZADO A-307 DE 3/4 X 8', 'CONS', 'central', 'insumo'),
    ('TORNILLO GALVANIZADA A-307 DE 3/8 X 5', 'CONS', 'central', 'insumo'),
    ('TORNILLO GALVANIZADA A-307 DE 3/4 X 8', 'CONS', 'central', 'insumo'),
    ('TUERCA NEGRA A-325 DE 1 1/2', 'CONS', 'central', 'insumo'),
    ('TORNILLO NEGRO A-325 DE 1 1/4 X 4', 'CONS', 'central', 'insumo'),
    ('TONILLO NEGRO A-325 DE 1 1/2 X 4 3/4', 'CONS', 'central', 'insumo'),
    ('TORNILLO GALVANIZADO A-307 DE 1/4 X 2 1/2', 'CONS', 'central', 'insumo'),
    ('TORNILLO NEGRO A-325 DE 1 1/2 X 4 7/8', 'CONS', 'central', 'insumo'),
    ('TORNILLO GALVANIZADO A-325 DE 1/2 X 6 1/2', 'CONS', 'central', 'insumo'),
    ('TAQUETE EXPANISIVO DE 3/8 X 4', 'CONS', 'central', 'insumo'),
    ('TORNILLO CONTROL VOLT A-490 DE 1 1/8 X 3', 'CONS', 'central', 'insumo'),
    ('TORNILLO NEGRO A-325 DE 1/2 X 6 1/2', 'CONS', 'central', 'insumo'),
    ('TAQUETE EXPANSIVO DE 3/8 X 3', 'CONS', 'central', 'insumo'),
    ('TUERCA GALVANIZADO A-325 DE 7/8', 'CONS', 'central', 'insumo'),
    ('TORNILLO GALVANIZADO A-325 DE 7/8 X 2 1/4', 'CONS', 'central', 'insumo'),
    ('TORNILLO GALVANIZADO A-307 DE 1/2 X 5 1/2', 'CONS', 'central', 'insumo'),
    ('TORNILLO GALVANIZADO A-307 DE 3/8 X 8', 'CONS', 'central', 'insumo'),
    ('TUERCA GALVANIZADO A-325 DE 1', 'CONS', 'central', 'insumo'),
    ('RONDANA NEGRA A-325 DE 1 1/4', 'CONS', 'central', 'insumo'),
    ('RONDANA NEGRA A-325 DE 1 3/8', 'CONS', 'central', 'insumo'),
    ('RONDANA NEGRA A-325 DE 1', 'CONS', 'central', 'insumo'),
    ('TORNILLO NEGRO A-325 DE 3/8 X 8', 'CONS', 'central', 'insumo'),
    ('TORNILLO CONTROL VOLT A-490 1 1/8 X 3 1/2', 'CONS', 'central', 'insumo'),
    ('TORNILLO NEGRO A-325 DE 1/2 X 8', 'CONS', 'central', 'insumo'),
    ('RONDANA NEGRA A-436 DE 1', 'CONS', 'central', 'insumo'),
    ('RONDANA GALVANIZADA A-307 1/2', 'CONS', 'central', 'insumo'),
    ('RONDANA GALVANIZADA A-307 DE 2', 'CONS', 'central', 'insumo'),
    ('RONDANA GALVANIZADA A-307 DE 1 1/2', 'CONS', 'central', 'insumo'),
    ('RONDANA GALVANIZADA A-307 DE 1 3/8', 'CONS', 'central', 'insumo'),
    ('TORNILLO NEGRO A-325 DE 1 X 3 3/4', 'CONS', 'central', 'insumo'),
    ('TORNILLO CONTROL VOLT A-490 DE 1 1/8 X 3 1/4', 'CONS', 'central', 'insumo'),
    ('TORNILLO NEGRO A-325 DE 1 1/4 X 3 3/4', 'CONS', 'central', 'insumo'),
    ('TORNILLO GALVANIZADO A-325 DE 1/2 X 1 1/4', 'CONS', 'central', 'insumo'),
    ('TORNILLO NEGRO A-325 DE 1 1/8 X 4', 'CONS', 'central', 'insumo'),
    ('TORNILLO GALVANIZADO A-325 DE 1 1/8 X 3 1/2', 'CONS', 'central', 'insumo'),
    ('TORNILLO NEGRO A-325 DE 1 1/8 X 3', 'CONS', 'central', 'insumo'),
    ('TORNILLO CONTROL VOLT NEGRO A-325 DE 1 X 2', 'CONS', 'central', 'insumo'),
    ('TORNILLO GALVANIZADO A-490 DE 1 1/2 X 4 1/2', 'CONS', 'central', 'insumo'),
    ('TORNILLO GALVANIZADO A-307 DE 3/8 X 2', 'CONS', 'central', 'insumo'),
    ('TORNILLO CONTROL VOLT NEGRO A-325 DE 7/8 X 2', 'CONS', 'central', 'insumo'),
    ('TORNILLO GALVANIZADO A-325 DE 1 1/2 X 4 1/2', 'CONS', 'central', 'insumo'),
    ('TORNILLO NEGRO A-325 DE 1 1/4 X 4 1/4', 'CONS', 'central', 'insumo'),
    ('TORNILLO NEGRO A-490 1 1/2 X 4 1/2', 'CONS', 'central', 'insumo'),
    ('TORNILLO NEGRO A-325 DE 1 1/2 X 4 1/2', 'CONS', 'central', 'insumo'),
    ('TORNILLO NEGRO A-325 DE 1 1/4 X 3 1/2', 'CONS', 'central', 'insumo'),
    ('TORNILLO NEGRO A-325 DE 3/4 X 2', 'CONS', 'central', 'insumo'),
    ('TORNILLO GALVANIZADO A-307 DE 1/2 X 1 1/4', 'CONS', 'central', 'insumo'),
    ('TORNILLO NEGRO A-325 DE 1 1/2 X 4 3/4', 'CONS', 'central', 'insumo'),
    ('TORNILLO NEGRO A-325  DE 1 1/2 X 4 1/2', 'CONS', 'central', 'insumo'),
    ('TORNILLO GALVANIZADO A-307 DE 1 1/2 X 4 1/2', 'CONS', 'central', 'insumo'),
    ('TORNILLO NEGRO A-325 DE 1 1/8 X 4 3/4', 'CONS', 'central', 'insumo'),
    ('TORNILLO NEGRO A-325 DE 1 X 4', 'CONS', 'central', 'insumo'),
    ('TORNILLO NEGRO A-325 DE 1 1/8 X 4 1/4', 'CONS', 'central', 'insumo'),
    ('TORNILLO NEGRO A-325 DE 1 1/2 X 3 1/2', 'CONS', 'central', 'insumo'),
    ('TORNILLO GALVANIZADO A-307 DE 1 1/4 X 3 3/4', 'CONS', 'central', 'insumo'),
    ('TORNILLO NEGRO A-325 DE 1 1/2 X 5', 'CONS', 'central', 'insumo'),
    ('TORNILLO CONTROL VOLT DE 7/8 X 2 1/4', 'CONS', 'central', 'insumo'),
    ('TORNILLO NEGRO A-325 DE 1 1/4 X 3', 'CONS', 'central', 'insumo'),
    ('TORNILLO CONTROL VOLT A-490 1 1/8 X 3 1/4', 'CONS', 'central', 'insumo'),
    ('TORNILLO CONTROL VOLT A-490 3 3/4 X 1 1/8', 'CONS', 'central', 'insumo'),
    ('TORNILLO NEGRO A-325 DE 1 1/4 X 3 1/4', 'CONS', 'central', 'insumo'),
    ('TORNILLO NEGRO A-325 DE 7/8 X 1 3/4', 'CONS', 'central', 'insumo'),
    ('TORNILLO GALVANIZADO A-325 DE 1 1/4 X 4', 'CONS', 'central', 'insumo'),
    ('TORNILLO NEGRO A-325 DE 1 1/8 X 3 3/4', 'CONS', 'central', 'insumo'),
    ('TORNILLO GALVANIZADO A-307 DE 1/2 X 2', 'CONS', 'central', 'insumo'),
    ('TORNILLO GALVANIZADO A-325 DE 1 1/4 X 4 3/4', 'CONS', 'central', 'insumo'),
    ('TORNILLO GALVANIZADO A-307 DE 3/8 X 2 1/2', 'CONS', 'central', 'insumo'),
    ('TUERCA GALVANIZADA A-307 DE 9/16', 'CONS', 'central', 'insumo'),
    ('TORNILLO NEGRO A-325 DE 1 X 3 1/2', 'CONS', 'central', 'insumo'),
    ('TORNILLO NEGRO A-325 1 X 3', 'CONS', 'central', 'insumo'),
    ('TONILLO NEGRO A-325 DE 1 X 3', 'CONS', 'central', 'insumo'),
    ('TORNILLO NEGRO A-490 DE 1 1/2 X 4 1/2', 'CONS', 'central', 'insumo'),
    ('TORNILLO GALVANIZADA A-307 DE 1 1/4 X 4 1/2', 'CONS', 'central', 'insumo'),
    ('TORNILLO NEGRO A-325 DE 7/8 X 4 1/8', 'CONS', 'central', 'insumo'),
    ('TUERCA GALVANIZADA A-307 DE 5/8', 'CONS', 'central', 'insumo'),
    ('TUERCA GALVANIZADA A-307 DE 3/4', 'CONS', 'central', 'insumo'),
    ('TORNILLO GALVANIZADO A-325 DE 1 1/2 X 4', 'CONS', 'central', 'insumo'),
    ('TUERCA GALVANIZADA A-325 DE 1 1/4', 'CONS', 'central', 'insumo'),
    ('TORNILLO NEGRO A-325 DE 1', 'CONS', 'central', 'insumo'),
    ('TORNILLO ACERO NEGRO A-307 DE 1/2 X 1 1/4', 'CONS', 'central', 'insumo'),
    ('TUERCA ACERO NEGRO A-307 DE 1/2', 'CONS', 'central', 'insumo'),
    ('ROLDANA ACERO NEGRO A-307 DE 1/2', 'CONS', 'central', 'insumo'),
    ('TUERCA ACERO NEGRO A-307 DE 3/8', 'CONS', 'central', 'insumo'),
    ('TORNILLO CONTROL VOLT DE 1 1/8 X 10', 'CONS', 'central', 'insumo'),
    ('TUERCA NEGRA A-307 DE 1 1/8', 'CONS', 'central', 'insumo'),
    ('TORNILLO GALVANIZADA A-307 DE 5/16 X 1 1/4', 'CONS', 'central', 'insumo'),
    ('TORNILLO GALVANIZADO A-325 DE 7/8 X 2', 'CONS', 'central', 'insumo'),
    ('TOENILLO NEGRO A-325 DE 1 1/4 X 4', 'CONS', 'central', 'insumo'),
    ('TUERCA NEGRA A-325 DE 1', 'CONS', 'central', 'insumo'),
    ('TORNILLO NEGRO A-325 DE 7/8 X 3', 'CONS', 'central', 'insumo'),
    ('TUERCA GALVANIZADA A325 DE 5/8', 'CONS', 'central', 'insumo'),
    ('TORNILLO GALVANIZADO A-325 DE 1 1/8 X 3 3/4', 'CONS', 'central', 'insumo'),
    ('TORNILLO GALVANIZADO  A-325 DE 3/4 X 3 3/4', 'CONS', 'central', 'insumo'),
    ('TORNILLO GALVANIZADA A-307 DE 1 X 2', 'CONS', 'central', 'insumo'),
    ('TORNILLO GALVANIZADA A-307 DE 1 1/4 X 4', 'CONS', 'central', 'insumo'),
    ('TORNILLO GALVANIZADO A-307 DE 3/8 X 1 3/4', 'CONS', 'central', 'insumo'),
    ('TORNILLO GALVANIZADO A-307 DE 1/2 X 9', 'CONS', 'central', 'insumo'),
    ('TORNILLO NEGRO A-325 DE 1 X 2 1/2', 'CONS', 'central', 'insumo'),
    ('TORNILLO NEGRO A-325 DE 1/2 X 1', 'CONS', 'central', 'insumo'),
    ('TORNILLO GALVANIZADO A-307 DE 1/2 X 7 1/2', 'CONS', 'central', 'insumo'),
    ('TORNILLO GALVANIZADO A-325 DE 1 X 3 3/4', 'CONS', 'central', 'insumo'),
    ('TAQUETE PARA PLASTICO 3/8', 'CONS', 'central', 'insumo'),
    ('TAQUETE EXPANSIVO DE 1/2', 'CONS', 'central', 'insumo'),
    ('TUERCA NEGRA A-325 3/4', 'CONS', 'central', 'insumo'),
    ('TUERCA GALVANIZADA A-325 1 1/4', 'CONS', 'central', 'insumo'),
    ('TUERCA GALVANIZADA A-325 DE 1', 'CONS', 'central', 'insumo'),
    ('TUERCA GALVANIZADA DE A-307 1/2', 'CONS', 'central', 'insumo'),
    ('TORNILLO GALVANIZDO A-307 1/2 X 7 1/2', 'CONS', 'central', 'insumo'),
    ('TORNILLO NEGRO A-325 1 1/2 X 4', 'CONS', 'central', 'insumo'),
    ('TUERCA NEGRA A-325 1 1/2', 'CONS', 'central', 'insumo'),
    ('TORNILLO CONTROL VOLT A-325 3/4 X 1 3/4', 'CONS', 'central', 'insumo'),
    ('TUERCA NEGRA DE A-325 3/4', 'CONS', 'central', 'insumo'),
    ('RONDANA GALVANIZADA F-436 1', 'CONS', 'central', 'insumo'),
    ('RONDANA NEGRA F-436 3/4', 'CONS', 'central', 'insumo'),
    ('VARILLA ROSCADA A325 1 MTS 5/8  GALVANIZADO', 'CONS', 'central', 'insumo'),
    ('VARILLA ROSCADA A325 1 MTS 3/4  GALVANIZADO', 'CONS', 'central', 'insumo'),
    ('VARILLA ROSCADA  A-307 1 MTS 1/2  GALVANIZADO', 'CONS', 'central', 'insumo'),
    ('VARILLA ROSCADA  A-325 1 MTS 1  NEGRO', 'CONS', 'central', 'insumo'),
    ('FERRULES', 'CONS', 'central', 'insumo'),
    ('TUERCA GALVANIZADA A325 3/4', 'CONS', 'central', 'insumo'),
    ('PIJA TEK 1/4 X 4', 'CONS', 'central', 'insumo'),
    ('TORNILLO HEXAGONAL GALVANIZADO A325 3/4 X 3 1/4', 'CONS', 'central', 'insumo'),
    ('PERNO NELSON 3/4 X 3 3/4', 'CONS', 'central', 'insumo'),
    ('PERNO NELSON 3/4 X 4 3/16', 'CONS', 'central', 'insumo'),
    ('PIJA TEEK 1/4 X 3', 'CONS', 'central', 'insumo'),
    ('TORNILLO GALVANIZADO A-325 1 3/16 X 4', 'CONS', 'central', 'insumo'),
    ('TORNILLO GALVANIZADO A-325 1/2 X 6 1/2', 'CONS', 'central', 'insumo'),
    ('TUERCA NEGRA A-325 7/8', 'CONS', 'central', 'insumo'),
    ('JUEGO DE ACC PARA PIJA TEEK', 'CONS', 'central', 'insumo'),
    ('RONDANA GALVANIZADA DE 3/4', 'CONS', 'central', 'insumo'),
    ('PIJA HEXAGONAL STAP 1/4 X 3/4', 'CONS', 'central', 'insumo'),
    ('TORNILLO GALVANIZADO A-307 DE 5/8 X 2', 'CONS', 'central', 'insumo'),
    ('TORNILLO HEXAGONAL GALVANIZADA A-307 DE 3/8 X 8', 'CONS', 'central', 'insumo'),
    ('TORNILLO CONTROL VOLT A-490 DE 7/8 X 3 1/4', 'CONS', 'central', 'insumo'),
    ('CONTROL VOLT A-490 4 1/4 x 1 1/2', 'CONS', 'central', 'insumo'),
    ('TORNILLO CONTROL VOLT  A-490 de 1 1/8 x 5 3/4', 'CONS', 'central', 'insumo'),
    ('TORNILLO NEGRO A-490 DE 1/2 X 7 1/2', 'CONS', 'central', 'insumo'),
    ('TORNILLO NEGRO A-325 DE 1 X 3', 'CONS', 'central', 'insumo'),
    ('CONTROL VOLT A-490 7/8 X 3 1/4', 'CONS', 'central', 'insumo'),
    ('TORNILLO CONTROL VOLT 1 1/8 X 4', 'CONS', 'central', 'insumo'),
    ('CONTROL VOLT A-490 1 1/8 X 10', 'CONS', 'central', 'insumo'),
    ('TORNILLO CONTROL VOLT 1 1/8 X 3 1/2', 'CONS', 'central', 'insumo'),
    ('CONTROL VOLT A-490 1 1/8 X 4 1/4', 'CONS', 'central', 'insumo'),
    ('TORNILLO CONTROL VOLT A-490 DE 5/8 X 2 1/4', 'CONS', 'central', 'insumo'),
    ('CONTROL VOLT A-490 1 X 2 1/2', 'CONS', 'central', 'insumo'),
    ('TORNILLO GALVANIZADO A-307 DE 1/2 X 1 3/4', 'CONS', 'central', 'insumo'),
    ('TORNILLO GALVANIZADO A-307 DE 3/4 X 1 1/2', 'CONS', 'central', 'insumo'),
    ('CONTROL VOLT A-490 1 1/8 X 7', 'CONS', 'central', 'insumo'),
    ('TORNILLO NEGRO A-490 DE 3/4 X 3 3/4', 'CONS', 'central', 'insumo'),
    ('CONTROL VOLT A-490  1 1/8 X 6 1/2', 'CONS', 'central', 'insumo'),
    ('TORNILLO CONTROL VOLT A-490 1 1/8 X 5 3/4', 'CONS', 'central', 'insumo'),
    ('TORNILLO CONTROL VOLT A-490 DE 1 1/8 X 5 3/4', 'CONS', 'central', 'insumo'),
    ('TORNILLO CONTROL A-490 VOLT DE 1 1/8 X 5', 'CONS', 'central', 'insumo'),
    ('TORNILLO HEXAGONAL A-325 3/4 X 3 1/2', 'CONS', 'central', 'insumo'),
    ('TORNILLO GALVANIZADO A-325 DE 3/8 X 1 1/4', 'CONS', 'central', 'insumo'),
    ('TORNILLO CONTROL VOLT 3 1/4 X 1 1/8', 'CONS', 'central', 'insumo'),
    ('TORNILLO CONTROL VOLT  A-325 DE 7/8 X 3 1/4', 'CONS', 'central', 'insumo'),
    ('TORNILLO CONTROL VOLT A-490 DE 1 1/8 X 4 3/4', 'CONS', 'central', 'insumo'),
    ('TORNILLO NEGRO A-490 DE 1 1/8 X 3 3/4', 'CONS', 'central', 'insumo'),
    ('TORNILLO HEXAGONAL GALVANIZADO A-307 DE 1/2 X 8', 'CONS', 'central', 'insumo'),
    ('TUERCA GALVANIZADA A-325 DE 3/8', 'CONS', 'central', 'insumo'),
    ('TORNILLO HEXAGONAL A-325 5/8 X 2 1/2', 'CONS', 'central', 'insumo'),
    ('TORNILLO HEXAGONAL GALVANIZADO A307 DE 5/8 X 8', 'CONS', 'central', 'insumo'),
    ('TORNILLO CONTROL VOLT A-490 DE 3 1/4 X 1 1/8', 'CONS', 'central', 'insumo'),
    ('TORNILLO CONTROL VOLT A-490 DE 3 X 1 1/8', 'CONS', 'central', 'insumo'),
    ('TORNILLLO CONTROL VOLT A-490 DE 4 X 1 1/8', 'CONS', 'central', 'insumo'),
    ('TORNILLO CONTROL VOLT A-490 DE 1 X 10', 'CONS', 'central', 'insumo'),
    ('TORNILLO CONTROL VOLT A-490 DE 4 X 1 1/8', 'CONS', 'central', 'insumo'),
    ('TORNILLLO CONTROL VOLT A-490 DE 3 1/4 X 1 1/8', 'CONS', 'central', 'insumo'),
    ('TORNILLO NEGRO HEXAGONAL A-325 DE 5/8 X 1 3/4', 'CONS', 'central', 'insumo'),
    ('TORNILLO NEGRO HEXAGONAL A-325 DE 7/8 X 4 1/4', 'CONS', 'central', 'insumo'),
    ('TORNILLO NEGRO HENAGONAL A-325 DE 5/8 X 1 1/2', 'CONS', 'central', 'insumo'),
    ('TORNILLO NEGRO HEXAGONAL A-325 DE 3/4 X 4', 'CONS', 'central', 'insumo'),
    ('TORNILLO NEGRO HEXAGONAL A-325 DE 3/4 X 3 1/2', 'CONS', 'central', 'insumo'),
    ('TORNILLO NEGRO HEXAGONAL A-325 DE 7/8 X 3 3/4', 'CONS', 'central', 'insumo'),
    ('TORNILLO NEGRO HEXAGONAL A-325 DE 7/8 X 1 3/4', 'CONS', 'central', 'insumo'),
    ('TORNILLO NEGRO HEXAGONAL A-325 DE 3/4 X 3', 'CONS', 'central', 'insumo'),
    ('TORNILLO NEGRO HEXAGONAL A-325 DE 7/8 X 2 1/2', 'CONS', 'central', 'insumo'),
    ('Tobera tipo tweco 25 CT', 'INS', 'central', 'insumo'),
    ('Aceite corta acero 19L', 'INS', 'central', 'insumo'),
    ('Aislador para boquilla 35CT', 'INS', 'central', 'insumo'),
    ('Barbiquejo para casco', 'INS', 'central', 'insumo'),
    ('Boquilla 111 graco', 'INS', 'central', 'insumo'),
    ('Boquilla 211 graco', 'INS', 'central', 'insumo'),
    ('Boquilla 215 graco', 'INS', 'central', 'insumo'),
    ('Boquilla 217 graco', 'INS', 'central', 'insumo'),
    ('Boquilla 219 graco', 'INS', 'central', 'insumo'),
    ('Boquilla 221 graco', 'INS', 'central', 'insumo'),
    ('Boquilla 225 graco', 'INS', 'central', 'insumo'),
    ('Boquilla 321 graco', 'INS', 'central', 'insumo'),
    ('Boquilla 325 graco', 'INS', 'central', 'insumo'),
    ('Boquilla corte 6290NX2', 'INS', 'central', 'insumo'),
    ('Boquilla corte 6290NX3', 'INS', 'central', 'insumo'),
    ('Boquilla de oxicorte #0', 'INS', 'central', 'insumo'),
    ('Boquilla de oxicorte #1', 'INS', 'central', 'insumo'),
    ('Boquilla de oxicorte #2', 'INS', 'central', 'insumo'),
    ('Boquilla de oxicorte #3', 'INS', 'central', 'insumo'),
    ('Broca de 1/2', 'INS', 'central', 'insumo'),
    ('Broca de 1/4', 'INS', 'central', 'insumo'),
    ('Broca de 1/8', 'INS', 'central', 'insumo'),
    ('Broca de 3/16', 'INS', 'central', 'insumo'),
    ('Broca de 3/4', 'INS', 'central', 'insumo'),
    ('Broca de 3/8', 'INS', 'central', 'insumo'),
    ('Broca de 5/16', 'INS', 'central', 'insumo'),
    ('Broca de 5/8', 'INS', 'central', 'insumo'),
    ('Broca de 7/16', 'INS', 'central', 'insumo'),
    ('Broca de 9/16', 'INS', 'central', 'insumo'),
    ('Broca escalonada de 1/4 A 3/4"', 'INS', 'central', 'insumo'),
    ('Brocha de 1"', 'INS', 'central', 'insumo'),
    ('Brocha de 2"', 'INS', 'central', 'insumo'),
    ('Brocha de 3"', 'INS', 'central', 'insumo'),
    ('Brocha de 4"', 'INS', 'central', 'insumo'),
    ('Carda 3" estándar', 'INS', 'central', 'insumo'),
    ('Carda 4" tipo cónica multirosca cod. 14188', 'INS', 'central', 'insumo'),
    ('Carda 4" tipo plato cod. 14190', 'INS', 'central', 'insumo'),
    ('Carda 5"', 'INS', 'central', 'insumo'),
    ('Carda 3" multirosca M14X2 - 5/8', 'INS', 'central', 'insumo'),
    ('Careta de soldador', 'INS', 'central', 'insumo'),
    ('Careta facial', 'INS', 'central', 'insumo'),
    ('Cartucho p/vapores cabel', 'INS', 'central', 'insumo'),
    ('Cartucho para vapores orgánicos 3M', 'INS', 'central', 'insumo'),
    ('Casco  azul', 'INS', 'central', 'insumo'),
    ('Casco amarillo', 'INS', 'central', 'insumo'),
    ('Cepillo de alambre', 'INS', 'central', 'insumo'),
    ('Chaleco azul marino', 'INS', 'central', 'insumo'),
    ('Chaleco brigadista azul rey', 'INS', 'central', 'insumo'),
    ('Chaleco naranja malla', 'INS', 'central', 'insumo'),
    ('Chaleco tipo brigadista naranja', 'INS', 'central', 'insumo'),
    ('Chaleco tipo brigadista verde', 'INS', 'central', 'insumo'),
    ('Chispero', 'INS', 'central', 'insumo'),
    ('Cincel 12"', 'INS', 'central', 'insumo'),
    ('Cinta canela', 'INS', 'central', 'insumo'),
    ('Cinta de aislar', 'INS', 'central', 'insumo'),
    ('Cinta de seguridad roja', 'INS', 'central', 'insumo'),
    ('Cinta de señalización', 'INS', 'central', 'insumo'),
    ('Cinta masking tape 1"', 'INS', 'central', 'insumo'),
    ('Cinta masking tape 2"', 'INS', 'central', 'insumo'),
    ('Cinta métrica 30 MTS', 'INS', 'central', 'insumo'),
    ('Cinta teflon', 'INS', 'central', 'insumo'),
    ('Cizalla grande', 'INS', 'central', 'insumo'),
    ('Cordel', 'INS', 'central', 'insumo'),
    ('Crayola amarilla', 'INS', 'central', 'insumo'),
    ('Crayola azul', 'INS', 'central', 'insumo'),
    ('Cristal claro', 'INS', 'central', 'insumo'),
    ('Cristal sombra #11', 'INS', 'central', 'insumo'),
    ('Cristal sombra #12', 'INS', 'central', 'insumo'),
    ('Cristal sombra #13', 'INS', 'central', 'insumo'),
    ('Desengrasante 5 Lt', 'INS', 'central', 'insumo'),
    ('Desmoldante antiadherente', 'INS', 'central', 'insumo'),
    ('Difusor', 'INS', 'central', 'insumo'),
    ('Difusor de alta temperatura', 'INS', 'central', 'insumo'),
    ('Hojas tamaño doble carta', 'INS', 'central', 'insumo'),
    ('Hojas Tamaño Carta', 'INS', 'central', 'insumo'),
    ('Ácido muriático 1 Lt', 'INS', 'central', 'insumo'),
    ('Papel higiénico', 'INS', 'central', 'insumo'),
    ('Sarricida 1 Lt', 'INS', 'central', 'insumo'),
    ('Pastillas sanitarias', 'INS', 'central', 'insumo'),
    ('Jabón de tocador', 'INS', 'central', 'insumo'),
    ('Sanitas', 'INS', 'central', 'insumo'),
    ('Bolsa 50 x 70', 'INS', 'central', 'insumo'),
    ('Bolsa 60 x 90', 'INS', 'central', 'insumo'),
    ('Bolsa 90 x 1.20', 'INS', 'central', 'insumo'),
    ('Detergente polvo 10 Kg', 'INS', 'central', 'insumo'),
    ('Escoba cepillo', 'INS', 'central', 'insumo'),
    ('Recogedor', 'INS', 'central', 'insumo'),
    ('Mop completo 90 cm', 'INS', 'central', 'insumo'),
    ('Cloro 5 Lt', 'INS', 'central', 'insumo'),
    ('Difusor de gas tipo tweco 55 H', 'INS', 'central', 'insumo'),
    ('Difusor mig siisa', 'INS', 'central', 'insumo'),
    ('Difusor tweco HD54-16', 'INS', 'central', 'insumo'),
    ('220976 ESCUDO 125 AMP', 'INS', 'central', 'insumo'),
    ('220977 MANGA CAPUCHON125 AMP', 'INS', 'central', 'insumo'),
    ('220997 ANILLO 125 AMP', 'INS', 'central', 'insumo'),
    ('Disco de corte 4 1/2"', 'INS', 'central', 'insumo'),
    ('Disco de corte 7"', 'INS', 'central', 'insumo'),
    ('Disco de corte 9"', 'INS', 'central', 'insumo'),
    ('Disco de corte de 14"', 'INS', 'central', 'insumo'),
    ('Calculadora científica', 'INS', 'central', 'insumo'),
    ('Disco de desbaste  4 1/2"', 'INS', 'central', 'insumo'),
    ('Disco de desbaste 7"', 'INS', 'central', 'insumo'),
    ('Cartucho tinta negro 711', 'INS', 'central', 'insumo'),
    ('Cartucho tinta amarillo 711', 'INS', 'central', 'insumo'),
    ('Cartucho tinta magenta711', 'INS', 'central', 'insumo'),
    ('Disco de desbaste 9"', 'INS', 'central', 'insumo'),
    ('Disco laminado 4 1/2"', 'INS', 'central', 'insumo'),
    ('BK284123 ESCUDO 400 AMP', 'INS', 'central', 'insumo'),
    ('BK277266 RETENCION DE 200 AMP', 'INS', 'central', 'insumo'),
    ('BK284150 MANGAS/TAPA EXTERNA DE 400 AMP', 'INS', 'central', 'insumo'),
    ('BK284122 ANILLO 400 AMP', 'INS', 'central', 'insumo'),
    ('BK284124 ELECTRODO 400 AMP', 'INS', 'central', 'insumo'),
    ('Perforadora de 3 orificios', 'INS', 'central', 'insumo'),
    ('Disco laminado 7"', 'INS', 'central', 'insumo'),
    ('Electrodos de carbon ARCAI', 'INS', 'central', 'insumo'),
    ('Ensamble cuello omega 60 rinconera', 'INS', 'central', 'insumo'),
    ('Escoba insumos', 'INS', 'central', 'insumo'),
    ('Escuadra 12"', 'INS', 'central', 'insumo'),
    ('BK277286 ESCUDO 100 AMP', 'INS', 'central', 'insumo'),
    ('BK284125 BOQUILLA 400 AMP', 'INS', 'central', 'insumo'),
    ('Escuadra 24"', 'INS', 'central', 'insumo'),
    ('Limpiador de piso (AROMA)', 'INS', 'central', 'insumo'),
    ('Jabón líquido 1 Lt', 'INS', 'central', 'insumo'),
    ('Espátula', 'INS', 'central', 'insumo'),
    ('BK277270 ELECTRODO 275 AMP', 'INS', 'central', 'insumo'),
    ('BK277269 BOQUILLA DE 275 AMP', 'INS', 'central', 'insumo'),
    ('BK277263 ESCUDO DE 275 AMP', 'INS', 'central', 'insumo'),
    ('BK277258 ANILLO DIFUSOR 275 AMP', 'INS', 'central', 'insumo'),
    ('BK500695 GALON DE ANTOCONGELANTE P/MAQ LINCOLN', 'INS', 'central', 'insumo'),
    ('Estopa', 'INS', 'central', 'insumo'),
    ('Etiquetas plastificadas 9.5 X 6.5', 'INS', 'central', 'insumo'),
    ('Extintor 4.5kg', 'INS', 'central', 'insumo'),
    ('Extintor 6kg', 'INS', 'central', 'insumo'),
    ('Extintor 9kg', 'INS', 'central', 'insumo'),
    ('Faja talla grande', 'INS', 'central', 'insumo'),
    ('Faja talla mediana', 'INS', 'central', 'insumo'),
    ('Faja talla XL', 'INS', 'central', 'insumo'),
    ('Faja talla chica', 'INS', 'central', 'insumo'),
    ('Filo de segueta', 'INS', 'central', 'insumo'),
    ('Filtro lana p/mascarilla cabel', 'INS', 'central', 'insumo'),
    ('Filtro N95 3M', 'INS', 'central', 'insumo'),
    ('Fleje de acero pintado 3/4', 'INS', 'central', 'insumo'),
    ('Flexómetro de 10m', 'INS', 'central', 'insumo'),
    ('Flexómetro de 5m', 'INS', 'central', 'insumo'),
    ('Flexómetro de 8m', 'INS', 'central', 'insumo'),
    ('Fresa de desbaste para Rectificador de forma cilindrica Cod.190-102', 'INS', 'central', 'insumo'),
    ('Fresa de desbaste para Rectificador de forma conica Cod.190-122', 'INS', 'central', 'insumo'),
    ('Fresa de desbaste para Rectificador de forma ovalada Cod.190-120', 'INS', 'central', 'insumo'),
    ('Gel weld 500', 'INS', 'central', 'insumo'),
    ('Gis blanco', 'INS', 'central', 'insumo'),
    ('Gis para tiralíneas', 'INS', 'central', 'insumo'),
    ('Grapas para fleje', 'INS', 'central', 'insumo'),
    ('Guantes de bolita', 'INS', 'central', 'insumo'),
    ('Repuesto de mop 90 cm', 'INS', 'central', 'insumo'),
    ('Líquido trata mop 1 Lt', 'INS', 'central', 'insumo'),
    ('Mechudo de pabilo', 'INS', 'central', 'insumo'),
    ('Wiese aroma', 'INS', 'central', 'insumo'),
    ('Baygón verde', 'INS', 'central', 'insumo'),
    ('Limpia vidrios 1 Lt', 'INS', 'central', 'insumo'),
    ('Cepillo de plástico', 'INS', 'central', 'insumo'),
    ('Atomizador', 'INS', 'central', 'insumo'),
    ('Jalador para vidrios', 'INS', 'central', 'insumo'),
    ('Paño de microfibra', 'INS', 'central', 'insumo'),
    ('Cepillo de mano', 'INS', 'central', 'insumo'),
    ('Lavatraste líquido 1 Lt', 'INS', 'central', 'insumo'),
    ('Guantes de carnaza cortos', 'INS', 'central', 'insumo'),
    ('Guantes de carnaza largos', 'INS', 'central', 'insumo'),
    ('Escoba veneciana', 'INS', 'central', 'insumo'),
    ('Deshollinador de sosqil', 'INS', 'central', 'insumo'),
    ('Mop completo 60 cm', 'INS', 'central', 'insumo'),
    ('Repuesto de mop 60 cm', 'INS', 'central', 'insumo'),
    ('Papel higiénico gold', 'INS', 'central', 'insumo'),
    ('Cubeta #12', 'INS', 'central', 'insumo'),
    ('Jerga 1 metro', 'INS', 'central', 'insumo'),
    ('Destupidor wc', 'INS', 'central', 'insumo'),
    ('Jabonera de tocador', 'INS', 'central', 'insumo'),
    ('Guantes de soldador', 'INS', 'central', 'insumo'),
    ('Guía slugger 1"', 'INS', 'central', 'insumo'),
    ('Guía slugger 2"', 'INS', 'central', 'insumo'),
    ('Jalador de aluminio 40 cm', 'INS', 'central', 'insumo'),
    ('Asiento para wc', 'INS', 'central', 'insumo'),
    ('Sobre de Nómina', 'INS', 'central', 'insumo'),
    ('Hojas tamaño oficio', 'INS', 'central', 'insumo'),
    ('Cartucho tinta cyan  711', 'INS', 'central', 'insumo'),
    ('Memoria USB 32 GB', 'INS', 'central', 'insumo'),
    ('Protector de hojas 100 pzs', 'INS', 'central', 'insumo'),
    ('Carpeta de 1/2"', 'INS', 'central', 'insumo'),
    ('Carpeta de 1"', 'INS', 'central', 'insumo'),
    ('Carpeta de 1 1/2"', 'INS', 'central', 'insumo'),
    ('Carpeta de 2"', 'INS', 'central', 'insumo'),
    ('Carpeta de 3"', 'INS', 'central', 'insumo'),
    ('Carpeta de 4"', 'INS', 'central', 'insumo'),
    ('Carpeta de 5"', 'INS', 'central', 'insumo'),
    ('Bolígrafo rojo', 'INS', 'central', 'insumo'),
    ('Bolígrafo azul', 'INS', 'central', 'insumo'),
    ('Bolígrafo negro', 'INS', 'central', 'insumo'),
    ('Lapiz mirado #2', 'INS', 'central', 'insumo'),
    ('Borrador de goma', 'INS', 'central', 'insumo'),
    ('Caja de clip estándar', 'INS', 'central', 'insumo'),
    ('Calculadora', 'INS', 'central', 'insumo'),
    ('Cinta correctora', 'INS', 'central', 'insumo'),
    ('Repuesto para cutter', 'INS', 'central', 'insumo'),
    ('Folder amarillo', 'INS', 'central', 'insumo'),
    ('Caja de grapas', 'INS', 'central', 'insumo'),
    ('Separador 10 divisiones', 'INS', 'central', 'insumo'),
    ('Tabla con sujetador', 'INS', 'central', 'insumo'),
    ('Separador 15 divisiones', 'INS', 'central', 'insumo'),
    ('Libreta tabular', 'INS', 'central', 'insumo'),
    ('Plumón  para pizarrón', 'INS', 'central', 'insumo'),
    ('Caja de broches', 'INS', 'central', 'insumo'),
    ('Plumón permanente negro', 'INS', 'central', 'insumo'),
    ('Papel para plotter', 'INS', 'central', 'insumo'),
    ('Engrapadora', 'INS', 'central', 'insumo'),
    ('Memoria USB 16 GB', 'INS', 'central', 'insumo'),
    ('Carpeta Lefort', 'INS', 'central', 'insumo'),
    ('Marcatexto amarillo', 'INS', 'central', 'insumo'),
    ('Marcatexto rosa', 'INS', 'central', 'insumo'),
    ('Marcatexto naranja', 'INS', 'central', 'insumo'),
    ('Marcatexto verde', 'INS', 'central', 'insumo'),
    ('Marcatexto azul', 'INS', 'central', 'insumo'),
    ('Pegamento adhesivo', 'INS', 'central', 'insumo'),
    ('Regla metálica', 'INS', 'central', 'insumo'),
    ('Cera para contar', 'INS', 'central', 'insumo'),
    ('Tijera', 'INS', 'central', 'insumo'),
    ('Caja clip mariposa', 'INS', 'central', 'insumo'),
    ('Cinta adhesiva transparente', 'INS', 'central', 'insumo'),
    ('Caja clip jumbo', 'INS', 'central', 'insumo'),
    ('Cuaderno profesional Jean Book', 'INS', 'central', 'insumo'),
    ('Plumón base de agua 12 pzs', 'INS', 'central', 'insumo'),
    ('Cutter uso rudo', 'INS', 'central', 'insumo'),
    ('Plumones surtido delgados', 'INS', 'central', 'insumo'),
    ('Acetato para prueba de adherencia', 'INS', 'central', 'insumo'),
    ('Separador de 31 divisiones', 'INS', 'central', 'insumo'),
    ('Separador 8 divisiones', 'INS', 'central', 'insumo'),
    ('Separador 12 divisiones', 'INS', 'central', 'insumo'),
    ('220971 ELECTRODO 125 AMP', 'INS', 'central', 'insumo'),
    ('220975 BOQUILLA 125 AMP', 'INS', 'central', 'insumo'),
    ('Lentes claros', 'INS', 'central', 'insumo'),
    ('BK284121 CAPUCHON 400 AMP', 'INS', 'central', 'insumo'),
    ('BK277284 BOQUILLA 100 AMP', 'INS', 'central', 'insumo'),
    ('BK277282 ELECTRODO 100 AMP', 'INS', 'central', 'insumo'),
    ('BK277283 ANILLO DIFUSOR 100 AMP', 'INS', 'central', 'insumo'),
    ('420276 ELECTRODO 300 AMP', 'INS', 'central', 'insumo'),
    ('420491 ESCUDO PANTALLA SHIELD 300 AMP', 'INS', 'central', 'insumo'),
    ('420279 BOQUILLA (NOZZLE) 300 AMP', 'INS', 'central', 'insumo'),
    ('420406 ANILLO DIFUSOR 300 AMP', 'INS', 'central', 'insumo'),
    ('420261 BOQUILLA 170 AMP', 'INS', 'central', 'insumo'),
    ('420258 ELECTRODO 170 AMP', 'INS', 'central', 'insumo'),
    ('420513 ESCUDO 170 AMP', 'INS', 'central', 'insumo'),
    ('420260 ANILLO DIFUSOR 170 AMP', 'INS', 'central', 'insumo'),
    ('420231 ELECTRODO DE 50 AMP', 'INS', 'central', 'insumo'),
    ('420233 DIFUSOR DE 50 AMP', 'INS', 'central', 'insumo'),
    ('420234 BOQUILLA DE 50 AMP', 'INS', 'central', 'insumo'),
    ('420237 PANTALLA DE 50 AMP', 'INS', 'central', 'insumo'),
    ('420240 ELECTRODO DE 80 AMP', 'INS', 'central', 'insumo'),
    ('420242 DIFUSOR DE 80 AMP', 'INS', 'central', 'insumo'),
    ('420243 BOQUILLA DE 80 AMP', 'INS', 'central', 'insumo'),
    ('420246 PANTALLA DE 80 AMP', 'INS', 'central', 'insumo'),
    ('420249 ELECTRODO DE 130 AMP', 'INS', 'central', 'insumo'),
    ('420252 BOQUILLA DE 130 AMP', 'INS', 'central', 'insumo'),
    ('420255 PANTALLA DE 130 AMP', 'INS', 'central', 'insumo'),
    ('027055 LUBRICANTE XPR-300', 'INS', 'central', 'insumo'),
    ('72810570171 SIERRA LAMA 7880X41X3/4', 'INS', 'central', 'insumo'),
    ('72810570172 SIERRA LAMA 7880X41X13X4/6', 'INS', 'central', 'insumo'),
    ('420200 CAPUCHON 300 AMP', 'INS', 'central', 'insumo'),
    ('420368 TUBO REFRIGERANTE 300 AMP', 'INS', 'central', 'insumo'),
    ('220632 BOQUILLA 400 AMP', 'INS', 'central', 'insumo'),
    ('BK277130 ELECTRODO 30 AMP', 'INS', 'central', 'insumo'),
    ('BK277140 ANILLO DIFUSOR 30 AMP', 'INS', 'central', 'insumo'),
    ('BK277120 BOQUILLA 30 AMP', 'INS', 'central', 'insumo'),
    ('BK277122 BOQUILLA 50 AMP', 'INS', 'central', 'insumo'),
    ('BK277142 ANILLO DIFUSOR 70 AMP', 'INS', 'central', 'insumo'),
    ('BK277125 BOQUILLA 70 AMP', 'INS', 'central', 'insumo'),
    ('BK277153 CAPUCHON DE RETENCION 70 AMP', 'INS', 'central', 'insumo'),
    ('BK277293 BOQUILLA 150 AMP', 'INS', 'central', 'insumo'),
    ('028872 GALON DE SOLUCION REFRIGERANTE', 'INS', 'central', 'insumo'),
    ('Caja de ligas', 'INS', 'central', 'insumo'),
    ('Aire comprimido', 'INS', 'central', 'insumo'),
    ('Lentes némesis', 'INS', 'central', 'insumo'),
    ('Lentes obscuros', 'INS', 'central', 'insumo'),
    ('Lija 100', 'INS', 'central', 'insumo'),
    ('Lija 220', 'INS', 'central', 'insumo'),
    ('Lija 80', 'INS', 'central', 'insumo'),
    ('Llave stilson 10"', 'INS', 'central', 'insumo'),
    ('Llave stilson 12"', 'INS', 'central', 'insumo'),
    ('Mangas de carnaza', 'INS', 'central', 'insumo'),
    ('Marcal azul', 'INS', 'central', 'insumo'),
    ('Quita grapas', 'INS', 'central', 'insumo'),
    ('Cinta mágica', 'INS', 'central', 'insumo'),
    ('Marcal blanco', 'INS', 'central', 'insumo'),
    ('Caja de archivo muerto', 'INS', 'central', 'insumo'),
    ('Marcal amarillo', 'INS', 'central', 'insumo'),
    ('Tinta para sello negro', 'INS', 'central', 'insumo'),
    ('Cojín para sello mediano', 'INS', 'central', 'insumo'),
    ('Marcal rojo', 'INS', 'central', 'insumo'),
    ('Maroma para careta facial', 'INS', 'central', 'insumo'),
    ('Marrito de hule', 'INS', 'central', 'insumo'),
    ('Marro de 12 LBS', 'INS', 'central', 'insumo'),
    ('Marro de 4 LB', 'INS', 'central', 'insumo'),
    ('Carpeta colgante', 'INS', 'central', 'insumo'),
    ('Tapete liso basic', 'INS', 'central', 'insumo'),
    ('Martillo', 'INS', 'central', 'insumo'),
    ('Mascarilla con arnés doble cartucho', 'INS', 'central', 'insumo'),
    ('BK277151 CAPUCHON DE RETENCION INTERIOR 100 A', 'INS', 'central', 'insumo'),
    ('Charola modular negra', 'INS', 'central', 'insumo'),
    ('Mascarilla media cara 3M-6200', 'INS', 'central', 'insumo'),
    ('Block de solicitud de empleo', 'INS', 'central', 'insumo'),
    ('Mica de careta facial', 'INS', 'central', 'insumo'),
    ('Mini felpa', 'INS', 'central', 'insumo'),
    ('Mini maneral', 'INS', 'central', 'insumo'),
    ('Fibra blanca  146 X 92', 'INS', 'central', 'insumo'),
    ('Mop completo 90 cm producción', 'INS', 'central', 'insumo'),
    ('Nivel de 12"', 'INS', 'central', 'insumo'),
    ('Nivel de 24"', 'INS', 'central', 'insumo'),
    ('Perico de 12"', 'INS', 'central', 'insumo'),
    ('Petos (mandiles)', 'INS', 'central', 'insumo'),
    ('Piedra de chispero', 'INS', 'central', 'insumo'),
    ('Cesto para  basura jumbo', 'INS', 'central', 'insumo'),
    ('Pintura en aerosol amarillo', 'INS', 'central', 'insumo'),
    ('SIERRA CINTA 1-1/2 X .50 X 7.88', 'INS', 'central', 'insumo'),
    ('Pintura en aerosol azul', 'INS', 'central', 'insumo'),
    ('MAGNUM CONTACT 3/16', 'INS', 'central', 'insumo'),
    ('Pintura en aerosol azul marino', 'INS', 'central', 'insumo'),
    ('Pintura en aerosol blanco', 'INS', 'central', 'insumo'),
    ('Pintura en aerosol BYP rojo', 'INS', 'central', 'insumo'),
    ('Guantes satinado rojo', 'INS', 'central', 'insumo'),
    ('Pintura en aerosol naranja', 'INS', 'central', 'insumo'),
    ('Pintura en aerosol verde', 'INS', 'central', 'insumo'),
    ('Pinza de presión 10"', 'INS', 'central', 'insumo'),
    ('Pinza de presión tipo C', 'INS', 'central', 'insumo'),
    ('Pinza de punta y corte', 'INS', 'central', 'insumo'),
    ('Polainas (boteras)', 'INS', 'central', 'insumo'),
    ('BOQUILLA 420365', 'INS', 'central', 'insumo'),
    ('Porta difusor omega 3 rosc rinconera', 'INS', 'central', 'insumo'),
    ('Limpia cristales env. 5 Lt', 'INS', 'central', 'insumo'),
    ('Portapunta', 'INS', 'central', 'insumo'),
    ('Prenza de 30', 'INS', 'central', 'insumo'),
    ('Punta 0.45 para máquina DELTA MIG 657', 'INS', 'central', 'insumo'),
    ('Punta 0.52 para máquina DELTA MIG 657', 'INS', 'central', 'insumo'),
    ('Punta de contacto 0.45', 'INS', 'central', 'insumo'),
    ('BRUSH CEPILLO CIRCULAR PARA SIERRA', 'INS', 'central', 'insumo'),
    ('Punta de contacto 0.52', 'INS', 'central', 'insumo'),
    ('Punta de contacto 1.6', 'INS', 'central', 'insumo'),
    ('Punta de contacto 15H-116', 'INS', 'central', 'insumo'),
    ('Punta de contacto mig siisa 0.045', 'INS', 'central', 'insumo'),
    ('Punta de contacto mig siisa 0.052', 'INS', 'central', 'insumo'),
    ('Punta de contacto rinconera 0.45', 'INS', 'central', 'insumo'),
    ('Punta de contacto tweco 16S52', 'INS', 'central', 'insumo'),
    ('Repuesto mop 90 CM producción', 'INS', 'central', 'insumo'),
    ('Retenedor de prefiltro 3M', 'INS', 'central', 'insumo'),
    ('Fibra de metal', 'INS', 'central', 'insumo'),
    ('Ribbon 110*74 resina ER-100 P/Zebra', 'INS', 'central', 'insumo'),
    ('ANTORCHA DURAMAX 125 AMP', 'INS', 'central', 'insumo'),
    ('Notas adhesivas', 'INS', 'central', 'insumo'),
    ('Sacapuntas', 'INS', 'central', 'insumo'),
    ('Dispensdor de papel', 'INS', 'central', 'insumo'),
    ('Cuaderno con espiral forma francesa', 'INS', 'central', 'insumo'),
    ('Sargento 8"', 'INS', 'central', 'insumo'),
    ('Slinga 2" X 4m', 'INS', 'central', 'insumo'),
    ('Slinga 4" X 6m', 'INS', 'central', 'insumo'),
    ('Slugger 1/2 X1"', 'INS', 'central', 'insumo'),
    ('Slugger 11/16 DE 1"', 'INS', 'central', 'insumo'),
    ('Elemento odourstop chico', 'INS', 'central', 'insumo'),
    ('Slugger 1-13/16X1"', 'INS', 'central', 'insumo'),
    ('Slugger 1-15/16 X 1"', 'INS', 'central', 'insumo'),
    ('Slugger 15/16X2"', 'INS', 'central', 'insumo'),
    ('Soplete de corte oxígeno-acetileno', 'INS', 'central', 'insumo'),
    ('Suspensión para casco de seguridad', 'INS', 'central', 'insumo'),
    ('Plumón negro permanente punta delgada', 'INS', 'central', 'insumo'),
    ('Tapones auditivos', 'INS', 'central', 'insumo'),
    ('Tiralíneas', 'INS', 'central', 'insumo'),
    ('Boquilla para corte butano tricónica 261-0', 'INS', 'central', 'insumo'),
    ('Boquilla para corte butano tricónica 261-1', 'INS', 'central', 'insumo'),
    ('Boquilla para corte butano tricónica 261-2', 'INS', 'central', 'insumo'),
    ('Boquilla de corte tipo Víctor #1', 'INS', 'central', 'insumo'),
    ('Tobera', 'INS', 'central', 'insumo'),
    ('Tobera mig siisa 400A', 'INS', 'central', 'insumo'),
    ('Tobera para máquina DELTA MIG 655', 'INS', 'central', 'insumo'),
    ('Tobera tweco HD24-50', 'INS', 'central', 'insumo'),
    ('Rastrillo de jardín', 'INS', 'central', 'insumo'),
    ('Tobera tweco HD24-62', 'INS', 'central', 'insumo'),
    ('Trapos industriales', 'INS', 'central', 'insumo'),
    ('Cimpulse 51mp cubeta 19L', 'INS', 'central', 'insumo'),
    ('Toner brother TN1060 negro', 'INS', 'central', 'insumo'),
    ('WD-40 400ml', 'INS', 'central', 'insumo'),
    ('WD-40 DE 550 ml', 'INS', 'central', 'insumo'),
    ('Jalador de aluminio grande', 'MTO', 'central', 'insumo'),
    ('CLAVIJA DE 50 A 3P 250/600V', 'MTO', 'central', 'insumo'),
    ('CARBON 6018A BOSH', 'MTO', 'central', 'insumo'),
    ('CONTACTOR MAGNETICO S0, 25 AMP, 440V', 'MTO', 'central', 'insumo'),
    ('CABLE THW CAL 1/0 COLOR NEGRO', 'MTO', 'central', 'insumo'),
    ('TERMINAL ARILLO S/AISLAR DE 1/4 CAL 1/0', 'MTO', 'central', 'insumo'),
    ('CUBETA DE 19 LTS DE ACEITE HIDRULICO ISO 68', 'MTO', 'central', 'insumo'),
    ('FILTRO PARA ACEITE FS1212', 'MTO', 'central', 'insumo'),
    ('FILTRO PARA ACEITE WF2074', 'MTO', 'central', 'insumo'),
    ('FILTRO PARA ACEITE FF5269', 'MTO', 'central', 'insumo'),
    ('GUANTE DE ALGODÓN SEGURIDAD', 'MTO', 'central', 'insumo'),
    ('GUANTE PROTECCION ANTI IMPACTO', 'MTO', 'central', 'insumo'),
    ('OVEROL DESECHABLE', 'MTO', 'central', 'insumo'),
    ('BARNIZ S/AIRE ROJO 4LTS', 'MTO', 'central', 'insumo'),
    ('BOBINA MI 250CD-HF 300/250', 'MTO', 'central', 'insumo'),
    ('INTERRUPTOR MONOF . DE CUCHILLAS', 'MTO', 'central', 'insumo'),
    ('KIT TABLERO PORTABIRLO', 'MTO', 'central', 'insumo'),
    ('BOBINA MI2-300 CD', 'MTO', 'central', 'insumo'),
    ('PORTA CARRETA ARMADO PP4670', 'MTO', 'central', 'insumo'),
    ('MONOCOILD', 'MTO', 'central', 'insumo'),
    ('CIRCUITO RESET 10 AM 250 V', 'MTO', 'central', 'insumo'),
    ('PINZA DE TIERRA 600 AMP', 'MTO', 'central', 'insumo'),
    ('COLADOR DE ENTRADA A BOMBA 246385', 'MTO', 'central', 'insumo'),
    ('FILTRO DE BOMBA 287032', 'MTO', 'central', 'insumo'),
    ('PIEZA ORING 117828', 'MTO', 'central', 'insumo'),
    ('PIEZA ORING 103338', 'MTO', 'central', 'insumo'),
    ('TROAT SEAL LIQUID 206994', 'MTO', 'central', 'insumo'),
    ('ALCOHOL ISOPROPILICO', 'MTO', 'central', 'insumo'),
    ('AEROSOL LIMPIADOR Y DESENGRASANTE', 'MTO', 'central', 'insumo'),
    ('BALERO 6307-2Z/C3', 'MTO', 'central', 'insumo'),
    ('BALERO 6206-2Z/C3', 'MTO', 'central', 'insumo'),
    ('SELLO MECANICO LINEA A 1-1/4 PT-0131', 'MTO', 'central', 'insumo'),
    ('CLAVIJA 15A 2P+T 125V', 'MTO', 'central', 'insumo'),
    ('CONTACTO SENCILLO 2 P 3 HILOS', 'MTO', 'central', 'insumo'),
    ('MANIVELA CORRIENTE MI2300', 'MTO', 'central', 'insumo'),
    ('HORQUETA MOLDEADA GRANDE', 'MTO', 'central', 'insumo'),
    ('COLLARIN', 'MTO', 'central', 'insumo'),
    ('PERILLA CONMUTADORES', 'MTO', 'central', 'insumo'),
    ('ANTORCHA ABIMIG 450 5M BIZEL', 'MTO', 'central', 'insumo'),
    ('TERMINAL SIN AISLANTE 1/4 CAL 8', 'MTO', 'central', 'insumo'),
    ('SET DE JUNTAS Y VASO TEMP 10-12 VP002', 'MTO', 'central', 'insumo'),
    ('VALVULA ESFERA ROSC BCE 13MM 1/2', 'MTO', 'central', 'insumo'),
    ('KIT DE AGUJA DE PISTOLA PC 17Y297', 'MTO', 'central', 'insumo'),
    ('ARANDELA PREION GALVANIZADA 1/4', 'MTO', 'central', 'insumo'),
    ('JUEGO DE TERMINALES', 'MTO', 'central', 'insumo'),
    ('BOTON DE SEGURIDAD SF-799', 'MTO', 'central', 'insumo'),
    ('KIT LLAVE DE RETENCION SF-055', 'MTO', 'central', 'insumo'),
    ('EMBOLO FLUX 4.8 LPF SF-741', 'MTO', 'central', 'insumo'),
    ('KIT EMB REGULADOR P FLUX SF-054', 'MTO', 'central', 'insumo'),
    ('KIT RONDANAS SPUD 19 SF-057', 'MTO', 'central', 'insumo'),
    ('KIT DE RONDANAS SPUD 32 SF-058', 'MTO', 'central', 'insumo'),
    ('KIT MANIJA Y PEDAL D FLUX SF-056', 'MTO', 'central', 'insumo'),
    ('ESTOPERO SF-110', 'MTO', 'central', 'insumo'),
    ('RECEPTACULO QUICK DISCONNECT TORCH 420220', 'MTO', 'central', 'insumo'),
    ('ANTORNCHA PARA KRONOS DE COEXION 420221', 'MTO', 'central', 'insumo'),
    ('TUBO REFRIGERANTE 420368', 'MTO', 'central', 'insumo'),
    ('FILTRO DE AIRE', 'MTO', 'central', 'insumo'),
    ('BATERIA DE 12V 7AM', 'MTO', 'central', 'insumo'),
    ('CONJUNTO DE SUJECION 1/2 100098', 'MTO', 'central', 'insumo'),
    ('TAPA POSTERIOR PARA MI2300 PT1670', 'MTO', 'central', 'insumo'),
    ('RECEPTACULO DE 50 A 3P 250/600V', 'MTO', 'central', 'insumo'),
    ('ADAPTADOR PARA ANTORCHA PA0529', 'MTO', 'central', 'insumo'),
    ('TARJETA DE CONTROL DE MOTOR V2', 'MTO', 'central', 'insumo'),
    ('CONECTOR GLANDULA 13 MM', 'MTO', 'central', 'insumo'),
    ('TOMA DE CORRIENTE DUPLEX 2P 15 A 127 V', 'MTO', 'central', 'insumo'),
    ('PLACA DUPLEX ABS', 'MTO', 'central', 'insumo'),
    ('LINEAL CABLE DE USO RUDO 4X10', 'MTO', 'central', 'insumo'),
    ('PLACA IP-65 PARA RECEPTACULO DE 13MM', 'MTO', 'central', 'insumo'),
    ('ZAPATA PARA 500 AMP', 'MTO', 'central', 'insumo'),
    ('CONEXIÓN DE 90 GRADOS PARA FRENO DE AIRE 1/4 MACHO', 'MTO', 'central', 'insumo'),
    ('FILTRO DE ALTA EFICIENCIA 3M', 'MTO', 'central', 'insumo'),
    ('MANGUERA PARA BOMBA 246386', 'MTO', 'central', 'insumo'),
    ('MANGUERA SIN AIRE 1/4 X 50 6.4 MM X 15 M 277241', 'MTO', 'central', 'insumo'),
    ('HUESO DE MANIFOLD 15B071', 'MTO', 'central', 'insumo'),
    ('CARBONES DEWALT 34411', 'MTO', 'central', 'insumo'),
    ('FUSIBLE FLOAL 250 V F10AL250V', 'MTO', 'central', 'insumo'),
    ('SOLENOIDE 018F6714', 'MTO', 'central', 'insumo'),
    ('SOLENOIDE 032V7505', 'MTO', 'central', 'insumo'),
    ('SENSOR MECANICO PARA PIRAÑA', 'MTO', 'central', 'insumo'),
    ('TAPA DE VENTANA BLANCA 25611-30', 'MTO', 'central', 'insumo'),
    ('EMPAQUES PARA GATO HIDRAULICO 50TON 14850', 'MTO', 'central', 'insumo'),
    ('CARBONES BOSCH WH004-A96', 'MTO', 'central', 'insumo'),
    ('CARBONES BOSCH 1.619.P11.715', 'MTO', 'central', 'insumo'),
    ('TABLILLA DE ALIMENTACION 220V-440V LODESTAR', 'MTO', 'central', 'insumo'),
    ('FILTRO SEPARADOR DE AGUA Y ACEITE 19027', 'MTO', 'central', 'insumo'),
    ('NUDO DE 1/8 44082', 'MTO', 'central', 'insumo'),
    ('ABRAZADERA DE ACERO INOXIDABLE 44235 AB-10', 'MTO', 'central', 'insumo'),
    ('COPLE MACHO 1/4 19085', 'MTO', 'central', 'insumo'),
    ('VALVULA ELECTRONEUMATICA 7062040102', 'MTO', 'central', 'insumo'),
    ('TAPA RECTANGULAR 01.02.0427', 'MTO', 'central', 'insumo'),
    ('VALVULA ELECTRONEUMATICA 706204010', 'MTO', 'central', 'insumo'),
    ('FILTRO DE ACEITE CORIMPEX', 'MTO', 'central', 'insumo'),
    ('INTERRUPTOR TERMOMAGNETICO ABB 63A', 'MTO', 'central', 'insumo'),
    ('ACCESORIO DE FRENO KONEGRANES 210V', 'MTO', 'central', 'insumo'),
    ('FILTRO DE AIRE PARA LINCOLN SPIRIT', 'MTO', 'central', 'insumo'),
    ('BASE TRIPOLAR', 'MTO', 'central', 'insumo'),
    ('FILTRO DE AIRE DONALDSON', 'MTO', 'central', 'insumo'),
    ('FILTRO DE ANTICONGELANTE LINCOLN SPIRIT', 'MTO', 'central', 'insumo'),
    ('FILTRO DE ACEITE DONALDSON', 'MTO', 'central', 'insumo'),
    ('BASE DE ELECTROVALVULA LINCOLN', 'MTO', 'central', 'insumo'),
    ('CABLE DE COMUNICACIÓN 109114', 'MTO', 'central', 'insumo'),
    ('MANGUERA DE OXICORTE GEMINI CNC', 'MTO', 'central', 'insumo'),
    ('CONTROLES KONEGRANES (BOTONERA)', 'MTO', 'central', 'insumo'),
    ('CONTACTOR SIEMES 40A 400V', 'MTO', 'central', 'insumo'),
    ('CONTACTOR TRIPOLAR 40A-600V', 'MTO', 'central', 'insumo'),
    ('CONTACTOR TRIPOLAR SIEMES 220V 35A', 'MTO', 'central', 'insumo'),
    ('CONTACTOR SIEMENS 24V-10A 220V-10A', 'MTO', 'central', 'insumo'),
    ('GUARDA MOTOR SIEMENS 24V-4A 220V-2A', 'MTO', 'central', 'insumo'),
    ('GUARDA MOTOR SIEMENS 24V-4A 220V-1.5A', 'MTO', 'central', 'insumo'),
    ('PASTILLA TERMOMAGNETICA 120/240V 15A', 'MTO', 'central', 'insumo'),
    ('PASTILLA TERMOMAGNETICA 120/240V 50A', 'MTO', 'central', 'insumo'),
    ('CABLE DE COMUNICACIÓN OXICORTE LINCOLN', 'MTO', 'central', 'insumo'),
    ('MANGUERA DE AIRE', 'MTO', 'central', 'insumo'),
    ('CENTRO DE ALIMENTACION CORTADORA BOSCH', 'MTO', 'central', 'insumo'),
    ('TEMPORIZADOR DE CORTE PUNTEO 5MD', 'MTO', 'central', 'insumo'),
    ('PT2287 TEMPORIZADOR DE CORTE PUNTO', 'MTO', 'central', 'insumo'),
    ('TARJETA DE CONTROL DEL VENTILADOR', 'MTO', 'central', 'insumo'),
    ('BOMBA DE VACIO VALUE', 'MTO', 'central', 'insumo'),
    ('NIVEL OPTICO BOSCH', 'MTO', 'central', 'insumo'),
    ('TRIPODES', 'MTO', 'central', 'insumo'),
    ('ARMADO SHUNT', 'MTO', 'central', 'insumo'),
    ('TABLERO PRIMARIO CON BARRENO PARA PORTA FUSIBLES', 'MTO', 'central', 'insumo'),
    ('SELECTOR DE RANGO', 'MTO', 'central', 'insumo'),
    ('MANIJA DE PLASTICO', 'MTO', 'central', 'insumo'),
    ('MANIVELA', 'MTO', 'central', 'insumo'),
    ('PORTA FUSIBLES', 'MTO', 'central', 'insumo'),
    ('Contactor tripolar KCL 690v – 25 A', 'MTO', 'central', 'insumo'),
    ('DIN5M TO DIN5F', 'MTO', 'central', 'insumo'),
    ('CABLE DE COMUNICACIÓN LINCOLN CNC', 'MTO', 'central', 'insumo'),
    ('FILTRO', 'MTO', 'central', 'insumo'),
    ('REPUESTO GRUA KONECRANES', 'MTO', 'central', 'insumo'),
    ('CONTACTOR TRIPOLAR WEG 1000V – 110 A', 'MTO', 'central', 'insumo'),
    ('COPLE Y ENGRASADORA SOMEY', 'MTO', 'central', 'insumo'),
    ('PLACA', 'MTO', 'central', 'insumo'),
    ('GRASA LODESTAR', 'MTO', 'central', 'insumo'),
    ('CARBON DWE4120', 'MTO', 'central', 'insumo'),
    ('73009216649 CONTROL UNIT', 'MTO', 'central', 'insumo'),
    ('RESORTE PARA CINTA INDICADORA', 'MTO', 'central', 'insumo'),
    ('TUBO NEGRO PVC P/MI2300', 'MTO', 'central', 'insumo'),
    ('CAPACITOR 17000 DELTA', 'MTO', 'central', 'insumo'),
    ('POTENCIOMETRO 2W 10K/ ALIMENTADOR', 'MTO', 'central', 'insumo'),
    ('INTERRUPTOR 2P 1T SRH-444', 'MTO', 'central', 'insumo'),
    ('73009216620 CARD 6SL3055', 'MTO', 'central', 'insumo'),
    ('CABLE USO RUDO 3X6', 'MTO', 'central', 'insumo'),
    ('COLECTOR TROLLEY MAS CABLE CL4-40', 'MTO', 'central', 'insumo'),
    ('LINEFEED CLAMP HOLDER RN4-LCH', 'MTO', 'central', 'insumo'),
    ('243222 CONTROL DE PRESION', 'MTO', 'central', 'insumo'),
    ('DEFLECTOR ROSCADO 241920', 'MTO', 'central', 'insumo'),
    ('ENGRANE 859 PARA TALADRO', 'MTO', 'central', 'insumo'),
    ('ANILLO ELASTICO 1.619.PB3.653', 'MTO', 'central', 'insumo'),
    ('RUEDA DE ENGRANE 1.619.PB3.652', 'MTO', 'central', 'insumo'),
    ('ENGRANE 54 PARA TALADRO', 'MTO', 'central', 'insumo'),
    ('ENGRANE 55 PARA TALADRO', 'MTO', 'central', 'insumo'),
    ('CABLE PORTAELECTRODO 4/0 AWG', 'MTO', 'central', 'insumo'),
    ('FUSIBLES CILINDRICO 2.00A 690V 14 X 51 MM', 'MTO', 'central', 'insumo'),
    ('BOQUILLA DE CONTACTO P/ARCO SUMERGIDO 3/32 1/8 5/3...', 'MTO', 'central', 'insumo'),
    ('GUANTE DIELECTRICO CLASE 1', 'MTO', 'central', 'insumo'),
    ('GUANTE DE NYLON C/PALMA DE NITRILO', 'MTO', 'central', 'insumo'),
    ('VALVULA NEUMATICA COD 228.52.2.1/2', 'MTO', 'central', 'insumo'),
    ('GUANTE DE LATEX EXT-LARGO', 'MTO', 'central', 'insumo'),
    ('CABLE PORTA ELECTRODO 2/0', 'MTO', 'central', 'insumo'),
    ('VALVULA SOLENOIDE 24 VAC. 50/60 HZ 4W', 'MTO', 'central', 'insumo'),
    ('PIVOTE DE MANGUERA 1/4GRUESO', 'MTO', 'central', 'insumo'),
    ('TUERCA P/MANGUERA DE ARGON 5/8', 'MTO', 'central', 'insumo'),
    ('TUERCA P/MANGUERA DE OXIGENO', 'MTO', 'central', 'insumo'),
    ('MINI ABRAZADERA REFORZADA 7/32-5/8', 'MTO', 'central', 'insumo'),
    ('23181512 RELAY ELECTRICO SOBRECARGA KIT 115V', 'MTO', 'central', 'insumo'),
    ('TRANSFORMADOR 500VA 440/220-110', 'MTO', 'central', 'insumo'),
    ('LIMPIADOR NBR85 NEGRO', 'MTO', 'central', 'insumo'),
    ('GUIA POM85 BLANCO', 'MTO', 'central', 'insumo'),
    ('GUIA HPU95 ROJO', 'MTO', 'central', 'insumo'),
    ('CONTACTOR ALBRIGHT SW80-6 24 V', 'MTO', 'central', 'insumo'),
    ('ARNES DE REPUESTO P/RESPIRADOR RES-600', 'MTO', 'central', 'insumo'),
    ('CINCHO DE PLASTICO 30 CM 50PZS', 'MTO', 'central', 'insumo'),
    ('CONDULET 1/2 CONEXIÓN TIPO FS VOLTECH', 'MTO', 'central', 'insumo'),
    ('SENSOR BARRERA 242731834000713', 'MTO', 'central', 'insumo'),
    ('RESPIRADOR MEDIA CARA DE SILICON 3M 7502', 'MTO', 'central', 'insumo'),
    ('CARBON 5196 1660 5455 MILWAUKEE', 'MTO', 'central', 'insumo'),
    ('CARBON DWE4557 DW490', 'MTO', 'central', 'insumo'),
    ('KIT DE TERMOFIT', 'MTO', 'central', 'insumo'),
    ('2625115 FILTRO COLECTOR RAZ', 'MTO', 'central', 'insumo'),
    ('228720 INTERRUPTOR DE SENSADO', 'MTO', 'central', 'insumo'),
    ('428147 CUERPO DE LA ANTORCHA', 'MTO', 'central', 'insumo'),
    ('428248 ACOPLE ANTORCHA', 'MTO', 'central', 'insumo'),
    ('428144 MANGUITO DE POSICIONAMIENTO', 'MTO', 'central', 'insumo'),
    ('FUSIBLE CILINDRICO 32 A, 3NC1432', 'MTO', 'central', 'insumo'),
    ('428642 KIT DE MANTENIMIENTO PREVENTIVO XPR300 8380...', 'MTO', 'central', 'insumo'),
    ('CONECTOR GLANDULA 25 MM', 'MTO', 'central', 'insumo'),
    ('CINCHO DE PLASTICO 2.5MMX100MM', 'MTO', 'central', 'insumo'),
    ('SOLDADURA DE PLATA 5', 'MTO', 'central', 'insumo'),
    ('TANQUE DE GAS NEGRO 14.1', 'MTO', 'central', 'insumo'),
    ('CORTADOR DE TUBO COBRE 1 1/4 PULG', 'MTO', 'central', 'insumo'),
    ('GUIA PARA CABLE', 'MTO', 'central', 'insumo'),
    ('168110 ORING', 'MTO', 'central', 'insumo'),
    ('ABRAZADERA DE 1/2 X 3/4', 'MTO', 'central', 'insumo'),
    ('2015865 MANGUERA AG DESCARGA Y SUCCION DE 2', 'MTO', 'central', 'insumo'),
    ('80-0184 SET GASKET KIT OF ROLLER', 'MTO', 'central', 'insumo'),
    ('ANTICONGELANTE 50/50 946 ML', 'MTO', 'central', 'insumo'),
    ('LC1D32F7 CONTACTOR AK1 440V, 3 POLOS BOBINA DE 110...', 'MTO', 'central', 'insumo'),
    ('LC1D09F7 CONTACTOR AK7 440V, 3 POLOS BOBINA DE 110...', 'MTO', 'central', 'insumo'),
    ('Llave de retención para fluxómetro de pedal HELVEX', 'MTO', 'central', 'insumo'),
    ('TARJETA DE CONTROL DELTA 655 PT1795R', 'MTO', 'central', 'insumo'),
    ('119-998 RESISTOR AE 5 OHM MR01495', 'MTO', 'central', 'insumo'),
    ('INVERSOR FINEARC300', 'MTO', 'central', 'insumo'),
    ('TORNILLO GALVANIZADO DE 1/4-20 X 1 1/2', 'MTO', 'central', 'insumo'),
    ('TUERCA GALVANIZADA 1/4-20', 'MTO', 'central', 'insumo'),
    ('INTERRUPTOR DE PURGA', 'MTO', 'central', 'insumo'),
    ('RECEPTACULO 4 PINES', 'MTO', 'central', 'insumo'),
    ('CINTA INDICADORA PC0428', 'MTO', 'central', 'insumo'),
    ('PTF0192', 'MTO', 'central', 'insumo'),
    ('SWITCH GRANDE BASICO SERIE BZ HONEYWELL', 'MTO', 'central', 'insumo'),
    ('EXTENSION USO RUDO 110 V', 'MTO', 'central', 'insumo'),
    ('TERMINAL COMPRESION TUBULAR 2/0 AWG 3/8', 'MTO', 'central', 'insumo'),
    ('INTERRUPTOR 1 POLO 1 TIRO', 'MTO', 'central', 'insumo'),
    ('EXTENSION TRIFASICA 440 V', 'MTO', 'central', 'insumo'),
    ('SENSOR BES M08EE PSC15BS04G+', 'MTO', 'central', 'insumo'),
    ('DREMEL', 'MTO', 'central', 'insumo'),
    ('SELECTOR ILUMINABLE 3 POSICIONES 22MM', 'MTO', 'central', 'insumo'),
    ('FUENTE DE PODER 1 FASE 2.5A 24 VDC', 'MTO', 'central', 'insumo'),
    ('FUENTE ENERGIA 88VCA-264 VCA A 48VCD-600W HYPERTHE...', 'MTO', 'central', 'insumo'),
    ('SELLADOR SHELLAC', 'MTO', 'central', 'insumo'),
    ('RUEDA PARA DIABLITO 8 DOBLE BALERO', 'MTO', 'central', 'insumo'),
    ('BOMBA DE AGUA DIAPHRAGM PUMP GMB 782432-070160 N 3...', 'MTO', 'central', 'insumo'),
    ('CHAPETON SPUD DE 38 MM', 'MTO', 'central', 'insumo'),
    ('CODO LATON PARA SPUD 38MM', 'MTO', 'central', 'insumo'),
    ('RELEVADOR SIEMENS 3RU2126-1GB0', 'MTO', 'central', 'insumo'),
    ('CABLE ELECTRICO CONDUMEX C-12', 'MTO', 'central', 'insumo'),
    ('GABINETE METALICO 40X60X25CM', 'MTO', 'central', 'insumo'),
    ('LIQUIDO PARA FRENOS DOT-3 900 ML', 'MTO', 'central', 'insumo'),
    ('DRIVE ROLL/GUIDE TUBE KIT KP1899-3', 'MTO', 'central', 'insumo'),
    ('VENTILADOR HYPERTHERM 229821', 'MTO', 'central', 'insumo'),
    ('MOTOR 1/8 HP', 'MTO', 'central', 'insumo'),
    ('ASPA DE 14 MA01082', 'MTO', 'central', 'insumo'),
    ('MANIVELA MAQUINADA PM0377', 'MTO', 'central', 'insumo'),
    ('VENTILADOR AXIAL 230V CUADRADO 119MM, 38MM, ROD. K...', 'MTO', 'central', 'insumo'),
    ('CARBON BRUSH 04549 SLUGGER 30798651180', 'MTO', 'central', 'insumo'),
    ('BALERO FAG 33209', 'MTO', 'central', 'insumo'),
    ('RUEDA PLACA GIRATORIA #PRE8977', 'MTO', 'central', 'insumo'),
    ('GIUNTO ROTANTE L9WM12620', 'MTO', 'central', 'insumo'),
    ('SUPPORTO PROXIMITY', 'MTO', 'central', 'insumo'),
    ('PCB (0151800244AE) TARJETA UNIDAD INTERIOR EVAPORA...', 'MTO', 'central', 'insumo'),
    ('TEMP. SENSOR SENSOR HUMEDAD', 'MTO', 'central', 'insumo'),
    ('SENSOR TEMPERATURE UNIDAD CONDENSADORA MARCA TRANE', 'MTO', 'central', 'insumo'),
    ('KIT COPLE PC / MANGUERA MANIFOLD 24W830', 'MTO', 'central', 'insumo'),
    ('TARJETA DE CONTROL PLACA 120V 246379', 'MTO', 'central', 'insumo'),
    ('MOTOREDUCTOR / MECANISMO ALIMENTADOR MM044412', 'MTO', 'central', 'insumo'),
    ('SEPARADOR DE 1/2 ABACUS, THS PS0741', 'MTO', 'central', 'insumo'),
    ('SEPARADOR DE 1/4 MI3-303 PS0737', 'MTO', 'central', 'insumo'),
    ('CAPACITOR DE 450V 4700MF PCB', 'MTO', 'central', 'insumo'),
    ('VARILLA, PISTON DE DESPLAZAMIENTO 19Y268', 'MTO', 'central', 'insumo'),
    ('BOBINA PRIM-SEC 3-375 PB1249', 'MTO', 'central', 'insumo'),
    ('ACEITE ISO 40 CNC /MEXLUB MR HIDRAULICO 19L', 'MTO', 'central', 'insumo'),
    ('TELAIO 2W0053600', 'MTO', 'central', 'insumo'),
    ('VITE SPECIALE 2W0228600', 'MTO', 'central', 'insumo'),
    ('KEY 9SM8776-5', 'MTO', 'central', 'insumo'),
    ('LIQUIDO REFRIGERANTE PLASMA ARC TORCH COOLANT CNC', 'MTO', 'central', 'insumo'),
    ('RESISTOR FIJO 200 OHM 5% 25W - MR06632', 'MTO', 'central', 'insumo'),
    ('Monocoild liner de acero siisa 0.035-0.045', 'MTO', 'central', 'insumo'),
    ('FILTRO ARMADO CP303 MI3-303', 'MTO', 'central', 'insumo'),
    ('ACEITE MULTIGRADO A GASOLINA 15W 40', 'MTO', 'central', 'insumo'),
    ('FILTRO DE ACEITE PH7317 OC707 MAHLE', 'MTO', 'central', 'insumo'),
    ('FILTRO DE AIRE PARA MOTOR HYG2200', 'MTO', 'central', 'insumo'),
    ('LAMPARA LED INDUSTRIAL 46794 200W', 'MTO', 'central', 'insumo'),
    ('PISTON GRACO/VARILLA DE DESPLAZAMIENTO 24W617', 'MTO', 'central', 'insumo'),
    ('TUBO LAMPARA LED 200W COD. 3468', 'MTO', 'central', 'insumo'),
    ('Monocoild tweco conduit standard 4411615', 'MTO', 'central', 'insumo'),
    ('CILINDRO PARA BOMBA PULVERIZADORA 24W619', 'MTO', 'central', 'insumo'),
    ('ORING 2-218 HELMEX', 'MTO', 'central', 'insumo'),
    ('BATERIA A06B-6073 K001- BATERIA PLC DE 6V', 'MTO', 'central', 'insumo'),
    ('BATERIA PANASONIC MOD. BR-2/3AGCT4A', 'MTO', 'central', 'insumo'),
    ('CONTACTOR VB7A-30-10-84 MINI REV', 'MTO', 'central', 'insumo'),
    ('SAL EN PELLET 20KG', 'MTO', 'central', 'insumo'),
    ('HIPOCLORITO DE SODIO 20L', 'MTO', 'central', 'insumo'),
    ('72810820032 GASKET HIT FOR ROLLER LIFTING HYDRAULI...', 'MTO', 'central', 'insumo'),
    ('PKM-400G MEMBRANA PARA SISTEMAS OSMOSIS INVERSA PU...', 'MTO', 'central', 'insumo'),
    ('PKCGAC2.5X20 FILTRO CARTUCHO DE CARBON ACTIVADO PU...', 'MTO', 'central', 'insumo'),
    ('PKCPP2.5X20X5 FILTRO CARTUCHO E POLIPROPILENO TERM...', 'MTO', 'central', 'insumo'),
    ('ESMERILADORA ANGULAR 9', 'MON', 'central', 'activo'),
    ('RECTIFICADOR O ESMERIL RECTO', 'MON', 'central', 'activo'),
    ('MINI ESMERIL DE 4 1/2', 'MON', 'central', 'activo'),
    ('SIERRA SABLE', 'MON', 'central', 'activo'),
    ('PIJADORA O ATORNILLADOR', 'MON', 'central', 'activo'),
    ('CORTADORA DE BANCO', 'MON', 'central', 'activo'),
    ('PISTOLA DE IMPACTO O DE TORQUE', 'MON', 'central', 'activo'),
    ('PISTOLA EPOXICO (SIN PILA)', 'MON', 'central', 'activo'),
    ('TALADRO MAGNETICO', 'MON', 'central', 'activo'),
    ('SOPLETE MULTIFLAMA', 'MON', 'central', 'activo'),
    ('HORNO PORTATIL P/SOLDADURA', 'MON', 'central', 'activo'),
    ('ESTACION NIVELADORA', 'MON', 'central', 'activo'),
    ('POLIPASTO 1 TONE', 'MON', 'central', 'activo'),
    ('POLIPASTO 2 TONE', 'MON', 'central', 'activo'),
    ('POLIPASTO 3 TONE', 'MON', 'central', 'activo'),
    ('POLIPASTO 5 TONE', 'MON', 'central', 'activo'),
    ('PISTOLA DE TORQUE INALAMBRICA', 'MON', 'central', 'activo'),
    ('PISTOLA CONTROLBOLT', 'MON', 'central', 'activo'),
    ('MAQUINAS DE SOLDAR INVERTER 220V 200 AMP', 'MON', 'central', 'activo'),
    ('ENGARGOLADORA', 'MON', 'central', 'activo'),
    ('MAQUINA DE SOLDAR MI2-300INFRA', 'MON', 'central', 'activo'),
    ('ESMERILADORA ANGULAR DE 9"', 'PROD', 'central', 'activo'),
    ('MINI ESMERIL DE 4 1/2', 'PROD', 'central', 'activo'),
    ('ROTO MARTILLO O TALADRO PERCUTOR', 'PROD', 'central', 'activo'),
    ('RECTIFICADOR O ESMERIL RECTO', 'PROD', 'central', 'activo'),
    ('TALADRO MAGNETICO', 'PROD', 'central', 'activo'),
    ('MAQUINAS DE SOLDAR INVERTER FINEARC300', 'PROD', 'central', 'activo'),
    ('CORTADORA DE BANCO', 'PROD', 'central', 'activo'),
    ('ESMERILADORA ANGULAR DE 9"', 'INS', 'central', 'activo'),
    ('MINI ESMERIL DE 4 1/2', 'INS', 'central', 'activo'),
    ('ROTO MARTILLO O TALADRO PERCUTOR', 'INS', 'central', 'activo'),
    ('RECTIFICADOR O ESMERIL RECTO', 'INS', 'central', 'activo'),
    ('TALADRO MAGNETICO', 'INS', 'central', 'activo'),
    ('MAQUINAS DE SOLDAR INVERTER FINEARC300', 'INS', 'central', 'activo'),
    ('GATO HIDRAULICO 50 TON', 'INS', 'central', 'activo'),
    ('MINI ESMERIL DE 4 1/2', 'MTO', 'central', 'activo'),
    ('ROTO MARTILLO O TALADRO PERCUTOR', 'MTO', 'central', 'activo'),
    ('MAQUINAS DE SOLDAR INVERTER FINEARC300', 'MTO', 'central', 'activo'),
    ('MAQUINAS DE SOLDAR INVERTER 220V 200 AMP', 'CONST', 'MBP', 'activo'),
    ('ARTORCHA ARCO AIRE', 'CONST', 'PARKS NAVE A', 'activo'),
    ('COMPRESOR INDUSTRIAL', 'CONST', 'PARKS NAVE A', 'activo'),
    ('MAQUINA DE SOLDAR MI2-300INFRA', 'CONST', 'PARKS NAVE A', 'activo'),
    ('GENERADOR A GASOLINA', 'CONST', 'PARKS NAVE A', 'activo'),
    ('PISTOLA DE IMPACTO O DE TORQUE', 'CONST', 'PARKS NAVE A', 'activo'),
    ('MINI ESMERIL DE 4 1/2', 'CONST', 'PARKS NAVE A', 'activo'),
    ('ROTO MARTILLO O TALADRO PERCUTOR', 'CONST', 'PARKS NAVE A', 'activo'),
    ('PISTOLA O LLAVE DE IMPACTO NEUMATICA', 'CONST', 'PARKS NAVE A', 'activo'),
    ('ESTACION TOTAL TOPOGRAFICA', 'CONST', 'SIX PARKS CANCUN', 'activo'),
    ('TRIPIE', 'CONST', 'SIX PARKS CANCUN', 'activo'),
    ('COMPRESOR INDUSTRIAL', 'CONST', 'TRES GUERRAS', 'activo'),
    ('RECTIFICADOR O ESMERIL RECTO', 'CONST', 'TRES GUERRAS', 'activo'),
    ('PISTOLA O LLAVE DE IMPACTO NEUMATICA', 'CONST', 'TRES GUERRAS', 'activo'),
    ('PISTOLA CONTROLBOLT', 'CONST', 'TRES GUERRAS', 'activo'),
    ('MULTIPLICADOR DE TORQUE', 'CONST', 'TRES GUERRAS', 'activo'),
    ('ARTORCHA ARCO AIRE', 'CONST', 'AMPLIACION T4', 'activo'),
    ('ESMERILADORA ANGULAR DE 9"', 'CONST', 'AMPLIACION T4', 'activo'),
    ('MINI ESMERIL DE 4 1/2', 'CONST', 'AMPLIACION T4', 'activo'),
    ('CORTADORA DE BANCO', 'CONST', 'AMPLIACION T4', 'activo'),
    ('RECTIFICADOR O ESMERIL RECTO', 'CONST', 'AMPLIACION T4', 'activo'),
    ('HORNO PORTATIL P/SOLDADURA', 'CONST', 'AMPLIACION T4', 'activo'),
    ('MAQUINAS DE SOLDAR INVERTER 220V 200 AMP', 'CONST', 'AMPLIACION T4', 'activo'),
    ('MAQUINA DE SOLDAR MI2-300INFRA', 'CONST', 'AMPLIACION T4', 'activo'),
    ('NIVEL LASER', 'CONST', 'AMPLIACION T4', 'activo'),
    ('PIJADORA O ATORNILLADOR', 'CONST', 'AMPLIACION T4', 'activo'),
    ('TALADRO MAGNETICO', 'CONST', 'AMPLIACION T4', 'activo'),
    ('ROTO MARTILLO O TALADRO PERCUTOR', 'CONST', 'AMPLIACION T4', 'activo'),
    ('PISTOLA DE IMPACTO O DE TORQUE', 'CONST', 'AMPLIACION T4', 'activo'),
    ('TORQUIMETRO', 'CONST', 'AMPLIACION T4', 'activo'),
    ('MULTIPLICADOR DE TORQUE', 'CONST', 'AMPLIACION T4', 'activo'),
    ('MEDIDOR DE ESPESOR DE PINTURA POSITECTOR', 'CONST', 'AMPLIACION T4', 'activo'),
    ('LIJADORA ORBITAL', 'CONST', 'AMPLIACION T4', 'activo'),
    ('SIERRA SABLE', 'CONST', 'TERRAZA ERNESTO ROSADO', 'activo')
)
SELECT  l.descripcion,
        l.almacen,
        l.obra,
        l.tipo,
        p.codigo        AS ya_existe_como,
        p.unidad,
        p.activo,
        (SELECT count(*) FROM alm_existencias e WHERE e.producto_id = p.id) AS tiene_existencia
FROM    layout l
JOIN    costos_productos p
       ON upper(trim(p.descripcion)) = upper(trim(l.descripcion))
ORDER BY l.almacen, l.obra, l.descripcion;
