<?php

namespace Database\Seeders\Alm;

/**
 * Padrón de activos de PROD (central): 7 artículos, 118 piezas, $381,735.36.
 */
class ProdActivosSeeder extends CargaInicialActivosSeeder
{
    protected function almacen(): string
    {
        return 'PROD';
    }

    /**
     * @return list<array{descripcion: string, unidad: string, area: string|null, abc: string, ubicacion: string|null, piezas: list<array<string, mixed>>}>
     */
    protected function articulos(): array
    {
        return [
            [
                'descripcion' => 'ESMERILADORA ANGULAR DE 9"',
                'unidad' => 'PZA',
                'area' => 'Herramienta',
                'abc' => 'C',
                'ubicacion' => '1.1-1.3',
                'piezas' => [
                    ['no_serie' => 'E066', 'costo' => 3508.62, 'marca' => 'Bosh', 'modelo' => null, 'id_mantenimiento' => null, 'estatus' => 'prestado', 'condicion' => 'Buen estado', 'observaciones' => null],
                    ['no_serie' => 'E084', 'costo' => 3508.62, 'marca' => 'Bosh', 'modelo' => null, 'id_mantenimiento' => null, 'estatus' => 'prestado', 'condicion' => 'Buen estado', 'observaciones' => null],
                    ['no_serie' => 'E105', 'costo' => 3508.62, 'marca' => 'Bosh', 'modelo' => null, 'id_mantenimiento' => null, 'estatus' => 'prestado', 'condicion' => 'Buen estado', 'observaciones' => null],
                    ['no_serie' => 'E106', 'costo' => 3508.62, 'marca' => 'Bosh', 'modelo' => null, 'id_mantenimiento' => null, 'estatus' => 'prestado', 'condicion' => 'Buen estado', 'observaciones' => null],
                    ['no_serie' => 'E062', 'costo' => 3508.62, 'marca' => 'Bosh', 'modelo' => null, 'id_mantenimiento' => null, 'estatus' => 'prestado', 'condicion' => 'Buen estado', 'observaciones' => null],
                    ['no_serie' => 'E089', 'costo' => 3508.62, 'marca' => 'Bosh', 'modelo' => null, 'id_mantenimiento' => null, 'estatus' => 'prestado', 'condicion' => 'Buen estado', 'observaciones' => null],
                    ['no_serie' => 'E116', 'costo' => 3508.62, 'marca' => 'Bosh', 'modelo' => null, 'id_mantenimiento' => null, 'estatus' => 'prestado', 'condicion' => 'Buen estado', 'observaciones' => null],
                    ['no_serie' => 'E026', 'costo' => 3508.62, 'marca' => 'Bosh', 'modelo' => null, 'id_mantenimiento' => null, 'estatus' => 'prestado', 'condicion' => 'Buen estado', 'observaciones' => null],
                    ['no_serie' => 'E072', 'costo' => 3508.62, 'marca' => 'Bosh', 'modelo' => null, 'id_mantenimiento' => null, 'estatus' => 'prestado', 'condicion' => 'Buen estado', 'observaciones' => null],
                    ['no_serie' => 'E104', 'costo' => 3508.62, 'marca' => 'Bosh', 'modelo' => null, 'id_mantenimiento' => null, 'estatus' => 'prestado', 'condicion' => 'Buen estado', 'observaciones' => null],
                    ['no_serie' => 'E077', 'costo' => 3508.62, 'marca' => 'Bosh', 'modelo' => null, 'id_mantenimiento' => null, 'estatus' => 'prestado', 'condicion' => 'Buen estado', 'observaciones' => null],
                    ['no_serie' => 'E081', 'costo' => 3508.62, 'marca' => 'Bosh', 'modelo' => null, 'id_mantenimiento' => null, 'estatus' => 'prestado', 'condicion' => 'Buen estado', 'observaciones' => null],
                    ['no_serie' => 'E118', 'costo' => 3508.62, 'marca' => 'Bosh', 'modelo' => null, 'id_mantenimiento' => null, 'estatus' => 'prestado', 'condicion' => 'Buen estado', 'observaciones' => null],
                    ['no_serie' => 'E073', 'costo' => 3508.62, 'marca' => 'Bosh', 'modelo' => null, 'id_mantenimiento' => null, 'estatus' => 'prestado', 'condicion' => 'Buen estado', 'observaciones' => null],
                    ['no_serie' => 'E114', 'costo' => 3508.62, 'marca' => 'Bosh', 'modelo' => null, 'id_mantenimiento' => null, 'estatus' => 'prestado', 'condicion' => 'Buen estado', 'observaciones' => null],
                    ['no_serie' => 'E141', 'costo' => 3508.62, 'marca' => 'Bosh', 'modelo' => null, 'id_mantenimiento' => null, 'estatus' => 'prestado', 'condicion' => 'Buen estado', 'observaciones' => null],
                    ['no_serie' => 'E058', 'costo' => 3508.62, 'marca' => 'Bosh', 'modelo' => null, 'id_mantenimiento' => null, 'estatus' => 'prestado', 'condicion' => 'Buen estado', 'observaciones' => null],
                    ['no_serie' => 'E078', 'costo' => 3508.62, 'marca' => 'Bosh', 'modelo' => null, 'id_mantenimiento' => null, 'estatus' => 'prestado', 'condicion' => 'Buen estado', 'observaciones' => null],
                    ['no_serie' => 'E143', 'costo' => 3508.62, 'marca' => 'Bosh', 'modelo' => null, 'id_mantenimiento' => null, 'estatus' => 'prestado', 'condicion' => 'Buen estado', 'observaciones' => null],
                    ['no_serie' => 'E079', 'costo' => 3508.62, 'marca' => 'Bosh', 'modelo' => null, 'id_mantenimiento' => null, 'estatus' => 'prestado', 'condicion' => 'Buen estado', 'observaciones' => null],
                    ['no_serie' => 'E036', 'costo' => 3508.62, 'marca' => 'Bosh', 'modelo' => null, 'id_mantenimiento' => null, 'estatus' => 'prestado', 'condicion' => 'Buen estado', 'observaciones' => null],
                    ['no_serie' => 'E087', 'costo' => 3508.62, 'marca' => 'Bosh', 'modelo' => null, 'id_mantenimiento' => null, 'estatus' => 'prestado', 'condicion' => 'Buen estado', 'observaciones' => null],
                    ['no_serie' => 'E093', 'costo' => 3508.62, 'marca' => 'Bosh', 'modelo' => null, 'id_mantenimiento' => null, 'estatus' => 'prestado', 'condicion' => 'Buen estado', 'observaciones' => null],
                    ['no_serie' => 'E108', 'costo' => 3508.62, 'marca' => 'Bosh', 'modelo' => null, 'id_mantenimiento' => null, 'estatus' => 'prestado', 'condicion' => 'Buen estado', 'observaciones' => null],
                    ['no_serie' => 'E057', 'costo' => 3508.62, 'marca' => 'Bosh', 'modelo' => null, 'id_mantenimiento' => null, 'estatus' => 'prestado', 'condicion' => 'Buen estado', 'observaciones' => null],
                    ['no_serie' => 'E111', 'costo' => 3508.62, 'marca' => 'Bosh', 'modelo' => null, 'id_mantenimiento' => null, 'estatus' => 'prestado', 'condicion' => 'Buen estado', 'observaciones' => null],
                    ['no_serie' => 'E101', 'costo' => 3508.62, 'marca' => 'Bosh', 'modelo' => null, 'id_mantenimiento' => null, 'estatus' => 'prestado', 'condicion' => 'Buen estado', 'observaciones' => null],
                    ['no_serie' => 'E099', 'costo' => 3508.62, 'marca' => 'Bosh', 'modelo' => null, 'id_mantenimiento' => null, 'estatus' => 'prestado', 'condicion' => 'Buen estado', 'observaciones' => null],
                    ['no_serie' => 'E113', 'costo' => 3508.62, 'marca' => 'Bosh', 'modelo' => null, 'id_mantenimiento' => null, 'estatus' => 'prestado', 'condicion' => 'Buen estado', 'observaciones' => null],
                    ['no_serie' => 'E119', 'costo' => 3508.62, 'marca' => 'Bosh', 'modelo' => null, 'id_mantenimiento' => null, 'estatus' => 'prestado', 'condicion' => 'Buen estado', 'observaciones' => null],
                    ['no_serie' => 'E142', 'costo' => 3508.62, 'marca' => 'Bosh', 'modelo' => null, 'id_mantenimiento' => null, 'estatus' => 'prestado', 'condicion' => 'Buen estado', 'observaciones' => null],
                    ['no_serie' => 'E060', 'costo' => 3508.62, 'marca' => 'Bosh', 'modelo' => null, 'id_mantenimiento' => null, 'estatus' => 'prestado', 'condicion' => 'Buen estado', 'observaciones' => null],
                    ['no_serie' => 'E069', 'costo' => 3508.62, 'marca' => 'Bosh', 'modelo' => null, 'id_mantenimiento' => null, 'estatus' => 'prestado', 'condicion' => 'Buen estado', 'observaciones' => null],
                    ['no_serie' => 'E173', 'costo' => 3508.62, 'marca' => 'Bosh', 'modelo' => null, 'id_mantenimiento' => null, 'estatus' => 'prestado', 'condicion' => 'Buen estado', 'observaciones' => null],
                    ['no_serie' => 'E013', 'costo' => 3508.62, 'marca' => 'DeWalt', 'modelo' => null, 'id_mantenimiento' => null, 'estatus' => 'prestado', 'condicion' => 'Buen estado', 'observaciones' => null],
                    ['no_serie' => 'E074', 'costo' => 3508.62, 'marca' => 'Bosh', 'modelo' => null, 'id_mantenimiento' => null, 'estatus' => 'prestado', 'condicion' => 'Buen estado', 'observaciones' => null],
                    ['no_serie' => 'E097', 'costo' => 3508.62, 'marca' => 'Bosh', 'modelo' => null, 'id_mantenimiento' => null, 'estatus' => 'prestado', 'condicion' => 'Buen estado', 'observaciones' => null],
                    ['no_serie' => 'E130', 'costo' => 3508.62, 'marca' => 'DeWalt', 'modelo' => null, 'id_mantenimiento' => null, 'estatus' => 'prestado', 'condicion' => 'Buen estado', 'observaciones' => null],
                    ['no_serie' => 'E110', 'costo' => 3508.62, 'marca' => 'Bosh', 'modelo' => null, 'id_mantenimiento' => null, 'estatus' => 'prestado', 'condicion' => 'Buen estado', 'observaciones' => null],
                    ['no_serie' => 'E117', 'costo' => 3508.62, 'marca' => 'Bosh', 'modelo' => null, 'id_mantenimiento' => null, 'estatus' => 'prestado', 'condicion' => 'Buen estado', 'observaciones' => null],
                    ['no_serie' => 'E160', 'costo' => 3508.62, 'marca' => 'Bosh', 'modelo' => null, 'id_mantenimiento' => null, 'estatus' => 'prestado', 'condicion' => 'Buen estado', 'observaciones' => null],
                    ['no_serie' => 'E100', 'costo' => 3508.62, 'marca' => 'Bosh', 'modelo' => null, 'id_mantenimiento' => null, 'estatus' => 'prestado', 'condicion' => 'Buen estado', 'observaciones' => null],
                    ['no_serie' => 'E071', 'costo' => 3508.62, 'marca' => 'Bosh', 'modelo' => null, 'id_mantenimiento' => null, 'estatus' => 'prestado', 'condicion' => 'Buen estado', 'observaciones' => null],
                    ['no_serie' => 'E068', 'costo' => 3508.62, 'marca' => 'Bosh', 'modelo' => null, 'id_mantenimiento' => null, 'estatus' => 'prestado', 'condicion' => 'Buen estado', 'observaciones' => null],
                    ['no_serie' => 'E091', 'costo' => 3508.62, 'marca' => 'bosh', 'modelo' => null, 'id_mantenimiento' => null, 'estatus' => 'prestado', 'condicion' => 'Buen estado', 'observaciones' => null],
                    ['no_serie' => 'E016', 'costo' => 3508.62, 'marca' => 'DeWalt', 'modelo' => null, 'id_mantenimiento' => null, 'estatus' => 'prestado', 'condicion' => 'Buen estado', 'observaciones' => null],
                ],
            ],
            [
                'descripcion' => 'MINI ESMERIL DE 4 1/2',
                'unidad' => 'PZA',
                'area' => 'Herramienta',
                'abc' => 'C',
                'ubicacion' => '1.1-1.3',
                'piezas' => [
                    ['no_serie' => 'M293', 'costo' => 1534, 'marca' => 'Bosh', 'modelo' => null, 'id_mantenimiento' => null, 'estatus' => 'prestado', 'condicion' => 'Buen estado', 'observaciones' => null],
                    ['no_serie' => 'M304', 'costo' => 1534, 'marca' => 'Bosh', 'modelo' => null, 'id_mantenimiento' => null, 'estatus' => 'prestado', 'condicion' => 'Buen estado', 'observaciones' => null],
                    ['no_serie' => 'M300', 'costo' => 1534, 'marca' => 'Bosh', 'modelo' => null, 'id_mantenimiento' => null, 'estatus' => 'prestado', 'condicion' => 'Buen estado', 'observaciones' => null],
                    ['no_serie' => 'M150', 'costo' => 1534, 'marca' => 'Bosh', 'modelo' => null, 'id_mantenimiento' => null, 'estatus' => 'prestado', 'condicion' => 'Buen estado', 'observaciones' => null],
                    ['no_serie' => 'M302', 'costo' => 1534, 'marca' => 'Bosh', 'modelo' => null, 'id_mantenimiento' => null, 'estatus' => 'prestado', 'condicion' => 'Buen estado', 'observaciones' => null],
                    ['no_serie' => 'M251', 'costo' => 1534, 'marca' => 'Bosh', 'modelo' => null, 'id_mantenimiento' => null, 'estatus' => 'prestado', 'condicion' => 'Buen estado', 'observaciones' => null],
                    ['no_serie' => 'M301', 'costo' => 1534, 'marca' => 'Bosh', 'modelo' => null, 'id_mantenimiento' => null, 'estatus' => 'prestado', 'condicion' => 'Buen estado', 'observaciones' => null],
                    ['no_serie' => 'M050', 'costo' => 1534, 'marca' => 'Bosh', 'modelo' => null, 'id_mantenimiento' => null, 'estatus' => 'prestado', 'condicion' => 'Buen estado', 'observaciones' => null],
                    ['no_serie' => 'M299', 'costo' => 1534, 'marca' => 'Bosh', 'modelo' => null, 'id_mantenimiento' => null, 'estatus' => 'prestado', 'condicion' => 'Buen estado', 'observaciones' => null],
                    ['no_serie' => 'M303', 'costo' => 1534, 'marca' => 'Bosh', 'modelo' => null, 'id_mantenimiento' => null, 'estatus' => 'prestado', 'condicion' => 'Buen estado', 'observaciones' => null],
                    ['no_serie' => 'M281', 'costo' => 1534, 'marca' => 'Bosh', 'modelo' => null, 'id_mantenimiento' => null, 'estatus' => 'prestado', 'condicion' => 'Buen estado', 'observaciones' => null],
                    ['no_serie' => 'M240', 'costo' => 1534, 'marca' => 'Bosh', 'modelo' => null, 'id_mantenimiento' => null, 'estatus' => 'prestado', 'condicion' => 'Buen estado', 'observaciones' => null],
                    ['no_serie' => 'M290', 'costo' => 1534, 'marca' => 'Bosh', 'modelo' => null, 'id_mantenimiento' => null, 'estatus' => 'prestado', 'condicion' => 'Buen estado', 'observaciones' => null],
                    ['no_serie' => 'M295', 'costo' => 1534, 'marca' => 'Bosh', 'modelo' => null, 'id_mantenimiento' => null, 'estatus' => 'prestado', 'condicion' => 'Buen estado', 'observaciones' => null],
                    ['no_serie' => 'M274', 'costo' => 1534, 'marca' => 'Bosh', 'modelo' => null, 'id_mantenimiento' => null, 'estatus' => 'prestado', 'condicion' => 'Buen estado', 'observaciones' => null],
                    ['no_serie' => 'M285', 'costo' => 1534, 'marca' => 'Bosh', 'modelo' => null, 'id_mantenimiento' => null, 'estatus' => 'prestado', 'condicion' => 'Buen estado', 'observaciones' => null],
                    ['no_serie' => 'M298', 'costo' => 1534, 'marca' => 'Bosh', 'modelo' => null, 'id_mantenimiento' => null, 'estatus' => 'baja', 'condicion' => 'dañado sin reparación', 'observaciones' => null],
                    ['no_serie' => 'M275', 'costo' => 1534, 'marca' => 'Bosh', 'modelo' => null, 'id_mantenimiento' => null, 'estatus' => 'prestado', 'condicion' => 'Buen estado', 'observaciones' => null],
                    ['no_serie' => 'M282', 'costo' => 1534, 'marca' => 'Bosh', 'modelo' => null, 'id_mantenimiento' => null, 'estatus' => 'prestado', 'condicion' => 'Buen estado', 'observaciones' => null],
                    ['no_serie' => 'M278', 'costo' => 1534, 'marca' => 'Bosh', 'modelo' => null, 'id_mantenimiento' => null, 'estatus' => 'prestado', 'condicion' => 'Buen estado', 'observaciones' => null],
                    ['no_serie' => 'M288', 'costo' => 1534, 'marca' => 'Bosh', 'modelo' => null, 'id_mantenimiento' => null, 'estatus' => 'prestado', 'condicion' => 'Buen estado', 'observaciones' => null],
                    ['no_serie' => 'M307', 'costo' => 1534, 'marca' => 'Bosh', 'modelo' => null, 'id_mantenimiento' => null, 'estatus' => 'prestado', 'condicion' => 'Buen estado', 'observaciones' => null],
                    ['no_serie' => 'M308', 'costo' => 1534, 'marca' => 'Bosh', 'modelo' => null, 'id_mantenimiento' => null, 'estatus' => 'prestado', 'condicion' => 'Buen estado', 'observaciones' => null],
                    ['no_serie' => 'M305', 'costo' => 1534, 'marca' => 'Bosh', 'modelo' => null, 'id_mantenimiento' => null, 'estatus' => 'prestado', 'condicion' => 'Buen estado', 'observaciones' => null],
                    ['no_serie' => 'M306', 'costo' => 1534, 'marca' => 'Bosh', 'modelo' => null, 'id_mantenimiento' => null, 'estatus' => 'prestado', 'condicion' => 'Buen estado', 'observaciones' => null],
                ],
            ],
            [
                'descripcion' => 'ROTO MARTILLO O TALADRO PERCUTOR',
                'unidad' => 'PZA',
                'area' => 'Herramienta',
                'abc' => 'C',
                'ubicacion' => '4.4-4.6',
                'piezas' => [
                    ['no_serie' => 'T57', 'costo' => 2932.2, 'marca' => 'Bosh', 'modelo' => null, 'id_mantenimiento' => null, 'estatus' => 'prestado', 'condicion' => 'Buen estado', 'observaciones' => null],
                    ['no_serie' => 'T15', 'costo' => 2932.2, 'marca' => 'Bosh', 'modelo' => null, 'id_mantenimiento' => null, 'estatus' => 'prestado', 'condicion' => 'Buen estado', 'observaciones' => null],
                    ['no_serie' => 'T53', 'costo' => 2932.2, 'marca' => 'Bosh', 'modelo' => null, 'id_mantenimiento' => null, 'estatus' => 'prestado', 'condicion' => 'Buen estado', 'observaciones' => null],
                    ['no_serie' => 'T56', 'costo' => 2932.2, 'marca' => 'Bosh', 'modelo' => null, 'id_mantenimiento' => null, 'estatus' => 'prestado', 'condicion' => 'Buen estado', 'observaciones' => null],
                    ['no_serie' => 'T48', 'costo' => 2932.2, 'marca' => 'Bosh', 'modelo' => null, 'id_mantenimiento' => null, 'estatus' => 'prestado', 'condicion' => 'Buen estado', 'observaciones' => null],
                ],
            ],
            [
                'descripcion' => 'RECTIFICADOR O ESMERIL RECTO',
                'unidad' => 'PZA',
                'area' => 'Herramienta',
                'abc' => 'C',
                'ubicacion' => '1.1-1.3',
                'piezas' => [
                    ['no_serie' => 'R046', 'costo' => 2448, 'marca' => 'Milwaukee', 'modelo' => null, 'id_mantenimiento' => null, 'estatus' => 'prestado', 'condicion' => 'Buen estado', 'observaciones' => null],
                    ['no_serie' => 'R051', 'costo' => 2448, 'marca' => 'Milwaukee', 'modelo' => null, 'id_mantenimiento' => null, 'estatus' => 'prestado', 'condicion' => 'Buen estado', 'observaciones' => null],
                    ['no_serie' => 'R061', 'costo' => 2448, 'marca' => 'Milwaukee', 'modelo' => null, 'id_mantenimiento' => null, 'estatus' => 'prestado', 'condicion' => 'Buen estado', 'observaciones' => null],
                    ['no_serie' => 'R078', 'costo' => 2448, 'marca' => 'Milwaukee', 'modelo' => null, 'id_mantenimiento' => null, 'estatus' => 'prestado', 'condicion' => 'Buen estado', 'observaciones' => null],
                    ['no_serie' => 'R079', 'costo' => 2448, 'marca' => 'Milwaukee', 'modelo' => null, 'id_mantenimiento' => null, 'estatus' => 'prestado', 'condicion' => 'Buen estado', 'observaciones' => null],
                    ['no_serie' => 'R082', 'costo' => 2448, 'marca' => 'Milwaukee', 'modelo' => null, 'id_mantenimiento' => null, 'estatus' => 'prestado', 'condicion' => 'Buen estado', 'observaciones' => null],
                    ['no_serie' => 'R006', 'costo' => 2448, 'marca' => 'Milwaukee', 'modelo' => null, 'id_mantenimiento' => null, 'estatus' => 'prestado', 'condicion' => 'Buen estado', 'observaciones' => null],
                    ['no_serie' => 'R042', 'costo' => 2448, 'marca' => 'Milwaukee', 'modelo' => null, 'id_mantenimiento' => null, 'estatus' => 'prestado', 'condicion' => 'Buen estado', 'observaciones' => null],
                    ['no_serie' => 'R081', 'costo' => 2448, 'marca' => 'Milwaukee', 'modelo' => null, 'id_mantenimiento' => null, 'estatus' => 'prestado', 'condicion' => 'Buen estado', 'observaciones' => null],
                    ['no_serie' => 'R020', 'costo' => 2448, 'marca' => 'Milwaukee', 'modelo' => null, 'id_mantenimiento' => null, 'estatus' => 'prestado', 'condicion' => 'Buen estado', 'observaciones' => null],
                    ['no_serie' => 'R022', 'costo' => 2448, 'marca' => 'Milwaukee', 'modelo' => null, 'id_mantenimiento' => null, 'estatus' => 'prestado', 'condicion' => 'Buen estado', 'observaciones' => null],
                    ['no_serie' => 'R041', 'costo' => 2448, 'marca' => 'Milwaukee', 'modelo' => null, 'id_mantenimiento' => null, 'estatus' => 'prestado', 'condicion' => 'Buen estado', 'observaciones' => null],
                    ['no_serie' => 'R044', 'costo' => 2448, 'marca' => 'Milwaukee', 'modelo' => null, 'id_mantenimiento' => null, 'estatus' => 'prestado', 'condicion' => 'Buen estado', 'observaciones' => null],
                    ['no_serie' => 'R048', 'costo' => 2448, 'marca' => 'Milwaukee', 'modelo' => null, 'id_mantenimiento' => null, 'estatus' => 'prestado', 'condicion' => 'Buen estado', 'observaciones' => null],
                    ['no_serie' => 'R062', 'costo' => 2448, 'marca' => 'Milwaukee', 'modelo' => null, 'id_mantenimiento' => null, 'estatus' => 'prestado', 'condicion' => 'Buen estado', 'observaciones' => null],
                    ['no_serie' => 'R070', 'costo' => 2448, 'marca' => 'Milwaukee', 'modelo' => null, 'id_mantenimiento' => null, 'estatus' => 'prestado', 'condicion' => 'Buen estado', 'observaciones' => null],
                    ['no_serie' => 'R072', 'costo' => 2448, 'marca' => 'Milwaukee', 'modelo' => null, 'id_mantenimiento' => null, 'estatus' => 'prestado', 'condicion' => 'Buen estado', 'observaciones' => null],
                    ['no_serie' => 'R074', 'costo' => 2448, 'marca' => 'Milwaukee', 'modelo' => null, 'id_mantenimiento' => null, 'estatus' => 'prestado', 'condicion' => 'Buen estado', 'observaciones' => null],
                    ['no_serie' => 'R075', 'costo' => 2448, 'marca' => 'Milwaukee', 'modelo' => null, 'id_mantenimiento' => null, 'estatus' => 'prestado', 'condicion' => 'Buen estado', 'observaciones' => null],
                    ['no_serie' => 'R076', 'costo' => 2448, 'marca' => 'Milwaukee', 'modelo' => null, 'id_mantenimiento' => null, 'estatus' => 'prestado', 'condicion' => 'Buen estado', 'observaciones' => null],
                    ['no_serie' => 'R047', 'costo' => 2448, 'marca' => 'Milwaukee', 'modelo' => null, 'id_mantenimiento' => null, 'estatus' => 'prestado', 'condicion' => 'Buen estado', 'observaciones' => null],
                    ['no_serie' => 'R050', 'costo' => 2448, 'marca' => 'Milwaukee', 'modelo' => null, 'id_mantenimiento' => null, 'estatus' => 'prestado', 'condicion' => 'Buen estado', 'observaciones' => null],
                    ['no_serie' => 'R064', 'costo' => 2448, 'marca' => 'Milwaukee', 'modelo' => null, 'id_mantenimiento' => null, 'estatus' => 'prestado', 'condicion' => 'Buen estado', 'observaciones' => null],
                    ['no_serie' => 'R071', 'costo' => 2448, 'marca' => 'Milwaukee', 'modelo' => null, 'id_mantenimiento' => null, 'estatus' => 'prestado', 'condicion' => 'Buen estado', 'observaciones' => null],
                    ['no_serie' => 'R068', 'costo' => 2448, 'marca' => 'Milwaukee', 'modelo' => null, 'id_mantenimiento' => null, 'estatus' => 'prestado', 'condicion' => 'Buen estado', 'observaciones' => null],
                    ['no_serie' => 'R012', 'costo' => 2448, 'marca' => 'Milwaukee', 'modelo' => null, 'id_mantenimiento' => null, 'estatus' => 'prestado', 'condicion' => 'Buen estado', 'observaciones' => null],
                    ['no_serie' => 'R054', 'costo' => 2448, 'marca' => 'Milwaukee', 'modelo' => null, 'id_mantenimiento' => null, 'estatus' => 'prestado', 'condicion' => 'Buen estado', 'observaciones' => null],
                    ['no_serie' => 'R024', 'costo' => 2448, 'marca' => 'Milwaukee', 'modelo' => null, 'id_mantenimiento' => null, 'estatus' => 'prestado', 'condicion' => 'Buen estado', 'observaciones' => null],
                    ['no_serie' => 'R033', 'costo' => 2448, 'marca' => 'Milwaukee', 'modelo' => null, 'id_mantenimiento' => null, 'estatus' => 'prestado', 'condicion' => 'Buen estado', 'observaciones' => null],
                    ['no_serie' => 'R057', 'costo' => 2448, 'marca' => 'Milwaukee', 'modelo' => null, 'id_mantenimiento' => null, 'estatus' => 'prestado', 'condicion' => 'Buen estado', 'observaciones' => null],
                ],
            ],
            [
                'descripcion' => 'TALADRO MAGNETICO',
                'unidad' => 'PZA',
                'area' => 'Herramienta',
                'abc' => 'C',
                'ubicacion' => '1.1',
                'piezas' => [
                    ['no_serie' => 'MG003', 'costo' => 14550, 'marca' => 'Bosh', 'modelo' => null, 'id_mantenimiento' => null, 'estatus' => 'prestado', 'condicion' => 'Buen estado', 'observaciones' => null],
                    ['no_serie' => 'MG004', 'costo' => 14550, 'marca' => 'Bosh', 'modelo' => null, 'id_mantenimiento' => null, 'estatus' => 'prestado', 'condicion' => 'Buen estado', 'observaciones' => null],
                    ['no_serie' => 'MG006', 'costo' => 14550, 'marca' => 'Bosh', 'modelo' => null, 'id_mantenimiento' => null, 'estatus' => 'prestado', 'condicion' => 'Buen estado', 'observaciones' => null],
                    ['no_serie' => 'MG010', 'costo' => 14550, 'marca' => 'Bosh', 'modelo' => null, 'id_mantenimiento' => null, 'estatus' => 'prestado', 'condicion' => 'Buen estado', 'observaciones' => null],
                ],
            ],
            [
                'descripcion' => 'MAQUINAS DE SOLDAR INVERTER FINEARC300',
                'unidad' => 'PZA',
                'area' => 'Herramienta',
                'abc' => 'C',
                'ubicacion' => '4.2',
                'piezas' => [
                    ['no_serie' => 'S04', 'costo' => 5237, 'marca' => 'MARAGA', 'modelo' => null, 'id_mantenimiento' => null, 'estatus' => 'prestado', 'condicion' => 'Buen estado', 'observaciones' => null],
                    ['no_serie' => 'S05', 'costo' => 5237, 'marca' => 'MARAGA', 'modelo' => null, 'id_mantenimiento' => null, 'estatus' => 'prestado', 'condicion' => 'Buen estado', 'observaciones' => null],
                    ['no_serie' => 'S09', 'costo' => 5237, 'marca' => 'MARAGA', 'modelo' => null, 'id_mantenimiento' => null, 'estatus' => 'prestado', 'condicion' => 'Buen estado', 'observaciones' => null],
                    ['no_serie' => 'S13', 'costo' => 5237, 'marca' => 'MARAGA', 'modelo' => null, 'id_mantenimiento' => null, 'estatus' => 'prestado', 'condicion' => 'Buen estado', 'observaciones' => null],
                ],
            ],
            [
                'descripcion' => 'CORTADORA DE BANCO',
                'unidad' => 'PZA',
                'area' => 'Herramienta',
                'abc' => 'C',
                'ubicacion' => 'HABILITADO',
                'piezas' => [
                    ['no_serie' => 'C45', 'costo' => 3684.96, 'marca' => 'Bosh', 'modelo' => null, 'id_mantenimiento' => null, 'estatus' => 'prestado', 'condicion' => 'Nuevo', 'observaciones' => null],
                    ['no_serie' => 'C46', 'costo' => 3684.96, 'marca' => 'Bosh', 'modelo' => null, 'id_mantenimiento' => null, 'estatus' => 'prestado', 'condicion' => 'Nuevo', 'observaciones' => null],
                    ['no_serie' => 'C47', 'costo' => 3684.96, 'marca' => 'Bosh', 'modelo' => null, 'id_mantenimiento' => null, 'estatus' => 'prestado', 'condicion' => 'Nuevo', 'observaciones' => null],
                    ['no_serie' => 'C48', 'costo' => 3684.96, 'marca' => 'Bosh', 'modelo' => null, 'id_mantenimiento' => null, 'estatus' => 'prestado', 'condicion' => 'Nuevo', 'observaciones' => null],
                ],
            ],
        ];
    }
}
